import type { WorkspaceLocale } from "@/frontend/features/dashboard/client/workspace-locale";

export function recruiterWorkspaceCopy(locale: WorkspaceLocale) {
  return locale === "vi"
    ? {
        company: "Công ty",
        allCompanies: "Tất cả công ty",
        ownedByYou: "Bạn sở hữu",
        memberAccess: "Quyền thành viên",
        settings: "CÀI ĐẶT CÔNG TY",
        teamSettings: "Cài đặt công ty / Đội ngũ",
        yourCompanies: "Công ty của bạn",
        switchCompanyHint:
          "Chuyển đổi hồ sơ công ty và ngữ cảnh đội ngũ được hiển thị bên dưới.",
        addOrJoinCompany: "Thêm hoặc tham gia công ty",
        ownershipLimitReached: (max: number) =>
          `Đã đạt giới hạn sở hữu (${max}/${max}). Bạn vẫn có thể tham gia công ty với vai trò Nhà tuyển dụng hoặc Quản lý nhân sự.`,
        ownershipUsage: (count: number, max: number) =>
          `Bạn đang sở hữu ${count}/${max} công ty. Tham gia công ty với vai trò Nhà tuyển dụng hoặc Quản lý nhân sự không sử dụng suất sở hữu.`,
        manageCompanyHint:
          "Bạn có thể quản lý hồ sơ, đội ngũ và cài đặt công ty.",
        invitedCompanyHint:
          "Các công ty đã mời bạn với vai trò nhà tuyển dụng hoặc quản lý.",
        slots: (count: number, max: number) => `${count}/${max} suất`,
        linked: (count: number) => `${count} liên kết`,
        noOwnedCompany: "Bạn chưa sở hữu công ty nào.",
        noOtherCompany: "Chưa có quyền truy cập công ty khác.",
        noCompanyTitle: "Chưa có công ty được liên kết",
        noCompanyDescription:
          "Trước tiên hãy hoàn tất xác minh nhà tuyển dụng. Sau khi được phê duyệt, trang này sẽ được liên kết với công ty bạn được ủy quyền quản lý.",
        createCompany: "Tạo công ty",
        keepIdentityUpToDate:
          "Giữ thông tin công ty dùng trong tin tuyển dụng và thẻ hiển thị cho ứng viên luôn được cập nhật.",
        verification: "Xác minh",
        verificationStatus: {
          approved: "Đã duyệt",
          rejected: "Bị từ chối",
          pending: "Đang chờ",
        },
        verifiedIdentity: "Danh tính đã xác minh",
        companyName: "Tên công ty",
        taxCode: "Mã số thuế",
        locked: "Đã khóa",
        lockedIdentityNote:
          "Thông tin này được khóa sau khi xác minh và không thể chỉnh sửa tại đây.",
        requestSupportChange: "Yêu cầu thay đổi qua bộ phận Hỗ trợ →",
        postingGate: "Điều kiện đăng tin",
        completeProfileBeforePosting:
          "Hãy hoàn thiện hồ sơ công ty trước khi đăng tin tuyển dụng",
        postingGateDescription:
          "Thao tác Tạo tin tuyển dụng vẫn bị khóa cho đến khi hoàn tất các trường này.",
        requiredField: "Trường bắt buộc",
        logoRequired: "Logo công ty là bắt buộc trước khi đăng tin tuyển dụng.",
        fieldsRequired: "Các trường có dấu * là bắt buộc.",
        industry: "Ngành nghề",
        companySize: "Quy mô công ty",
        address: "Địa chỉ",
        website: "Website",
        logo: "Logo công ty",
        logoPreview: "Xem trước logo công ty",
        logoHint: "PNG, JPEG hoặc WebP. Ảnh sẽ được thu nhỏ trước khi tải lên.",
        industryPlaceholder: "ví dụ: Công nghệ thông tin",
        sizePlaceholder: "ví dụ: 200–500 nhân viên",
        addressPlaceholder: "Đường, quận/huyện, thành phố",
        description: "Mô tả",
        savedProfile: "Hồ sơ công ty đã lưu",
        publicCompanyInfo: "Thông tin công ty công khai của bạn",
        saved: "Đã lưu",
        notProvided: "Chưa cung cấp",
        readOnlyNote: "Thông tin đã lưu hiện chỉ có thể xem.",
        ownership: "Quyền sở hữu",
        authorizedRecruiters: "Nhà tuyển dụng được ủy quyền",
        ownershipDescription:
          "Chỉ chủ sở hữu và các thành viên được liệt kê mới có thể quản lý tin tuyển dụng của công ty này.",
        authorizedOwner: "Chủ sở hữu được ủy quyền",
        unclaimed: "Chưa xác nhận",
        members: "Thành viên",
        manageTeam: "Quản lý đội ngũ",
        activeOwnerOnly:
          "Chỉ chủ sở hữu công ty đang hoạt động mới có thể quản lý thành viên đội ngũ.",
        dangerZone: "Khu vực nguy hiểm",
        dangerDescription:
          "Xóa vĩnh viễn công ty cùng toàn bộ việc làm, hồ sơ ứng tuyển, tin nhắn và dữ liệu phân tích. Thao tác này không thể hoàn tác.",
        deleteDialogDescription:
          "Thao tác này sẽ xóa vĩnh viễn công ty và dữ liệu nhà tuyển dụng, bao gồm tin tuyển dụng, hồ sơ ứng tuyển, tin nhắn và dữ liệu phân tích.",
        closeDeleteDialog: "Đóng hộp thoại xóa",
        typeToConfirm: "để xác nhận",
        cancel: "Hủy",
        removeLogo: "Xóa logo",
        chooseAnotherLogo: "Chọn logo khác",
        preparingLogo: "Đang chuẩn bị logo…",
        chooseLogo: "Chọn logo",
        saveProfile: "Lưu hồ sơ",
        saving: "Đang lưu…",
        editProfile: "Chỉnh sửa hồ sơ",
        deleteCompany: "Xóa công ty",
        deleteCompanyTitle: "Xóa công ty này?",
        deleteCompanyDescription:
          "Thao tác này không thể hoàn tác. Nhập chính xác tên công ty để xác nhận.",
        deleteConfirmation: (name: string) => `Nhập “${name}” để xác nhận`,
        keepCompany: "Giữ lại công ty",
        confirmDelete: "Xác nhận xóa",
        deleting: "Đang xóa…",
        profileSaved: "Đã lưu hồ sơ công ty.",
        logoReady: "Đã chuẩn bị bản xem trước logo. Hãy lưu hồ sơ để tải lên.",
        saveRequiredFields: "Hãy hoàn tất các trường bắt buộc trước khi lưu.",
        unableToSave: "Không thể lưu cài đặt công ty.",
        companyDeleted: "Đã xóa công ty.",
        unableToDelete: "Không thể xóa công ty.",
        chooseValidImage: "Hãy chọn tệp ảnh hợp lệ.",
        role: {
          owner: "Chủ sở hữu",
          recruiter: "Nhà tuyển dụng",
          hrManager: "Quản lý nhân sự",
          hiringManager: "Quản lý tuyển dụng",
          authorizedRecruiter: "Nhà tuyển dụng được ủy quyền",
          member: "Thành viên được ủy quyền",
        },
        team: {
          title: "Xây dựng đội ngũ tuyển dụng",
          description:
            "Mời đồng nghiệp đáng tin cậy và quản lý quyền truy cập công ty.",
          members: "Thành viên đội ngũ",
          memberCount: (count: number) => `${count} thành viên đội ngũ`,
          invite: "Mời đồng đội",
          inviteDescription:
            "Họ cần có tài khoản SmartHire trước khi chấp nhận lời mời.",
          workEmail: "Email công việc",
          sendInvitation: "Gửi lời mời",
          sending: "Đang gửi…",
          manageMembers: "Quản lý vai trò và quyền truy cập công ty.",
          total: (count: number) => `${count} tổng cộng`,
          makeRole: (role: string) => `Đổi thành ${role}`,
          restore: "Khôi phục",
          suspend: "Tạm ngưng",
          remove: "Xóa",
          primaryOwner: "Chủ sở hữu chính",
          pendingInvitations: "Lời mời đang chờ",
          statuses: {
            ACTIVE: "Đang hoạt động",
            SUSPENDED: "Tạm ngưng",
            REMOVED: "Đã xóa",
          },
          pendingCount: (count: number) => `${count} đang chờ`,
          pendingDescription: "Những người chưa tham gia công ty.",
          invitedAs: (role: string, date: string) =>
            `Được mời với vai trò ${role} · hết hạn ${date}`,
          revoke: "Thu hồi",
          noPending: "Không có lời mời đang chờ",
          noPendingDescription:
            "Dùng biểu mẫu phía trên để mời đồng đội đầu tiên.",
          activity: "Hoạt động đội ngũ",
          activityDescription:
            "Bản ghi bất biến gần đây về các thay đổi quyền truy cập.",
          recent: (count: number) => `${count} gần đây`,
          noActivity: "Chưa có hoạt động",
          noActivityDescription:
            "Các thao tác mời và quyền thành viên sẽ xuất hiện tại đây.",
          roleChanged: "Vai trò:",
          activityUpdated: "đã cập nhật",
          system: "Hệ thống",
          actions: {
            invited: "đã mời",
            accepted: "đã chấp nhận",
            declined: "đã từ chối",
            revoked: "đã thu hồi",
            changedTheRoleOf: "đã thay đổi vai trò của",
            suspended: "đã tạm ngưng",
            restored: "đã khôi phục",
            removed: "đã xóa",
          },
          invitationQueued: "Đã xếp hàng gửi lời mời",
          invitationQueuedDescription:
            "Người nhận có thể xem và phản hồi từ email SmartHire.",
          invitationNotSent: "Chưa gửi được lời mời",
          memberUpdated: "Đã cập nhật quyền thành viên.",
          invitationRevoked: "Đã thu hồi lời mời.",
          revokeConfirm:
            "Thu hồi lời mời đang chờ này? Người nhận sẽ không thể tham gia nữa.",
          removeConfirm: (name: string) => `Xóa ${name} khỏi công ty?`,
          invitationExists:
            "Email này đã có lời mời đang chờ. Hãy thu hồi lời mời đó trước khi gửi lời mời mới.",
          membershipExists: "Tài khoản này đã là thành viên công ty.",
          recipientUnavailable:
            "Không có tài khoản SmartHire đang hoạt động cho email này.",
          inviteFailed: "Không thể gửi lời mời này. Vui lòng thử lại.",
          updateFailed: "Không thể cập nhật thành viên.",
          revokeFailed: "Không thể thu hồi lời mời.",
        },
        jobManagement: {
          jobPostings: "Tin tuyển dụng",
          subtitle: "Quản lý mọi vị trí từ bản nháp đầu tiên đến khi kết thúc.",
          create: "Tạo tin tuyển dụng",
          yourOpenings: "TIN TUYỂN DỤNG CỦA BẠN",
          trackPipeline: "Theo dõi quy trình tuyển dụng",
          liveApplicantCounts: "Số lượng ứng viên trực tiếp",
          overview: "Tổng quan tin tuyển dụng",
          stats: {
            active: "Việc làm đang tuyển",
            applicants: "Tổng số ứng viên",
            pending: "Đang chờ duyệt",
            closing: "Sắp đóng",
          },
          tabs: {
            active: "Đang tuyển",
            draft: "Bản nháp",
            pending_approval: "Đang chờ duyệt",
            closed: "Đã đóng",
          },
          searchPostings: "Tìm tin tuyển dụng",
          searchPlaceholder: "Tìm theo chức danh hoặc phòng ban",
          department: "Phòng ban",
          allDepartments: "Tất cả phòng ban",
          skills: "Kỹ năng",
          arrangements: {
            ONSITE: "Tại văn phòng",
            HYBRID: "Kết hợp",
            REMOTE: "Từ xa",
          },
          statuses: {
            active: "Đang tuyển",
            draft: "Bản nháp",
            pending_approval: "Đang chờ duyệt",
            closed: "Đã đóng",
            rejected: "Bị từ chối",
          },
          reasonLabels: {
            INCOMPLETE_OR_UNCLEAR: "Thông tin chưa đầy đủ hoặc chưa rõ",
            MISLEADING_CONTENT: "Nội dung gây hiểu lầm",
            INAPPROPRIATE_LANGUAGE: "Ngôn ngữ không phù hợp",
            DUPLICATE_POSTING: "Tin đăng trùng lặp",
            INVALID_REQUIREMENTS: "Yêu cầu không hợp lệ",
            INSUFFICIENT_COMPENSATION: "Thiếu thông tin về đãi ngộ",
            VERIFICATION_MISMATCH: "Thông tin xác minh không khớp",
            PROHIBITED_CONTENT: "Nội dung bị cấm",
            OTHER: "Lý do khác",
          },
          updated: (value: string) => `Đã cập nhật ${value}`,
          today: "hôm nay",
          dayAgo: "1 ngày trước",
          daysAgo: (count: number) => `${count} ngày trước`,
          monthAgo: "1 tháng trước",
          monthsAgo: (count: number) => `${count} tháng trước`,
          locationNotSet: "Chưa đặt địa điểm",
          noDepartment: "Chưa có phòng ban",
          untitled: "Tin tuyển dụng chưa có tiêu đề",
          applicants: "Ứng viên",
          applicantsFor: (count: number, title: string) =>
            `${count} ứng viên cho ${title}`,
          viewPipeline: "Xem quy trình",
          viewPipelineFor: (title: string) => `Xem quy trình của ${title}`,
          reviseRejectedFor: (title: string) =>
            `Chỉnh sửa tin tuyển dụng bị từ chối: ${title}`,
          viewUnderReviewFor: (title: string) =>
            `Xem tin tuyển dụng đang được duyệt: ${title}`,
          viewClosedFor: (title: string) =>
            `Xem tin tuyển dụng đã đóng: ${title}`,
          editFor: (title: string) => `Chỉnh sửa tin tuyển dụng: ${title}`,
          revisePosting: "Chỉnh sửa tin",
          viewPosting: "Xem tin",
          editPosting: "Chỉnh sửa tin",
          deleteJob: "Xóa việc làm",
          extendDeadline: "Gia hạn hạn nộp",
          closeEarly: "Đóng sớm",
          deleteDraft: "Xóa bản nháp",
          withdrawToDraft: "Rút về bản nháp",
          reactivate: "Mở lại việc làm",
          reviewVersion: (sequence: number, state: string) =>
            `Phiên bản duyệt ${sequence}: ${state}`,
          reviewLocked:
            " — Phiên bản đã gửi bị khóa trong khi quản trị viên xem xét.",
          reviewStates: {
            APPROVED: "Đã duyệt",
            REJECTED: "Bị từ chối",
            PENDING: "Đang chờ duyệt",
            UNDER_REVIEW: "Đang xem xét",
          },
          rejectionFeedback: "Phản hồi từ chối",
          correctionRequest: "Quản trị viên yêu cầu chỉnh sửa",
          reviseAndResubmit: "Chỉnh sửa tin và gửi lại để yêu cầu duyệt mới.",
          approvedClosed:
            "Tin tuyển dụng đã duyệt này đã đóng và không còn nhận hồ sơ.",
          approvedVisible:
            "Tin tuyển dụng đã được duyệt và hiển thị cho ứng viên.",
          correctionGuidance:
            "Phiên bản đã duyệt vẫn đang hoạt động trong khi bạn chỉnh sửa và gửi phiên bản mới để duyệt.",
          companySetupRequired: "Cần thiết lập công ty",
          companySetupDescription:
            "Hãy liên kết một công ty thuộc sở hữu của nhà tuyển dụng trước khi tạo tin tuyển dụng. Với dữ liệu mock cục bộ, ownerUserId của công ty phải trùng với ID người dùng đang đăng nhập.",
          setupCompany: "Thiết lập công ty",
          profileActionRequired: "Cần thực hiện",
          completeProfile: "Hoàn thiện hồ sơ công ty trước khi đăng tin",
          profileLocked:
            "Tạo tin tuyển dụng bị khóa cho đến khi hoàn tất các trường sau.",
          openCompanySettings: "Mở cài đặt công ty",
          createFirst: "Tạo tin tuyển dụng đầu tiên",
          createNext: "Tạo tin tuyển dụng",
          empty: {
            active: [
              "Chưa có tin tuyển dụng đang hoạt động",
              "Các vị trí đã duyệt sẽ xuất hiện ở đây khi sẵn sàng cho ứng viên.",
            ],
            draft: [
              "Chưa có bản nháp",
              "Bắt đầu bằng một tin có cấu trúc và lưu lại khi bạn sẵn sàng tiếp tục.",
            ],
            pending_approval: [
              "Không có tin đang chờ duyệt",
              "Tin đã gửi sẽ ở đây cho đến khi quản trị viên duyệt hoặc yêu cầu chỉnh sửa.",
            ],
            closed: [
              "Chưa có tin đã đóng",
              "Các vị trí được đóng thủ công hoặc hết thời hạn nộp sẽ được lưu ở đây để tham khảo.",
            ],
            first: [
              "Tạo tin tuyển dụng đầu tiên",
              "Biến nhu cầu tuyển dụng tiếp theo thành cơ hội có cấu trúc, sẵn sàng cho ứng viên.",
            ],
          },
          confirm: {
            closeTitle: "Đóng việc làm sớm?",
            reactivateTitle: "Mở lại việc làm?",
            withdrawTitle: "Rút tin đã gửi?",
            deleteActiveTitle: "Xóa việc làm đang hoạt động?",
            deleteDraftTitle: "Xóa bản nháp?",
            closeLabel: "Đóng việc làm",
            reactivateLabel: "Mở lại việc làm",
            withdrawLabel: "Rút về bản nháp",
            deleteActiveLabel: "Xóa việc làm đang hoạt động",
            deleteDraftLabel: "Xóa bản nháp",
            closeDescription:
              "Tin này sẽ ngừng nhận hồ sơ mới và chuyển sang Đã đóng. Hồ sơ hiện có vẫn được giữ trong quy trình tuyển dụng.",
            reactivateDescription:
              "Tin này sẽ bắt đầu nhận hồ sơ mới và chuyển lại sang Đang tuyển.",
            withdrawDescription:
              "Tin sẽ rời hàng đợi duyệt của quản trị viên và trở về Bản nháp. Bạn có thể chỉnh sửa và gửi lại sau.",
            deleteActiveDescription:
              "Việc làm này sẽ bị xóa khỏi dữ liệu công khai và tìm kiếm ứng viên ngay lập tức. Hồ sơ ứng tuyển và lịch sử kiểm toán vẫn được giữ.",
            deleteDraftDescription:
              "Bản nháp này sẽ bị xóa vĩnh viễn. Thao tác này không thể hoàn tác.",
            cancel: "Hủy",
            processing: "Đang xử lý…",
          },
          errors: {
            load: "Không thể tải tin tuyển dụng.",
            close: "Không thể đóng tin tuyển dụng lúc này.",
            reactivate: "Không thể mở lại tin tuyển dụng lúc này.",
            delete: "Không thể xóa tin tuyển dụng lúc này.",
            withdraw: "Không thể rút tin tuyển dụng lúc này.",
          },
        },
        navigation: {
          workspace: "Không gian nhà tuyển dụng",
          overview: "Tổng quan",
          jobs: "Tin tuyển dụng",
          candidates: "Ứng viên",
          pipeline: "Quy trình",
          messages: "Tin nhắn tuyển dụng",
          settings: "Cài đặt công ty",
          soon: "Sắp có",
          signingOut: "Đang đăng xuất…",
          signOut: "Đăng xuất",
        },
        route: {
          jobPostings: "Tin tuyển dụng",
          loadingJobPostings: "Đang tải tin tuyển dụng",
          loadingJobPostingsDescription:
            "Đang tải các tin tuyển dụng và hoạt động tuyển dụng của bạn.",
          jobNotFound: "Không tìm thấy tin tuyển dụng",
          jobNotFoundDescription:
            "Tin này có thể đã bị xóa hoặc không còn khả dụng.",
          backToPostings: "Quay lại danh sách tin tuyển dụng",
        },
        filter: {
          ownedByYou: "Do bạn sở hữu",
          memberAccess: "Quyền thành viên",
        },
        messages: {
          ownerOversight: "Giám sát của chủ sở hữu",
          recruiterWorkspace: "Không gian nhà tuyển dụng",
          oversightTitle: "Giám sát tin nhắn tuyển dụng",
          title: "Tin nhắn tuyển dụng",
          description:
            "Mỗi cuộc trò chuyện thuộc về một hồ sơ ứng tuyển và một tin tuyển dụng.",
          conversations: "Cuộc trò chuyện tuyển dụng",
          searchCandidateOrJob: "Tìm ứng viên hoặc việc làm",
          searchPlaceholder: "Tìm tin nhắn",
          allCompanies: "Tất cả công ty",
          jobPosting: "Tin tuyển dụng",
          allJobPostings: "Tất cả tin tuyển dụng",
          assignment: "Phân công",
          assignedToMe: "Được phân công cho tôi",
          unassigned: "Chưa phân công",
          allCompanyThreads: "Tất cả cuộc trò chuyện công ty",
          unread: (count: number) => `${count} chưa đọc`,
          noMatching: "Không có cuộc trò chuyện phù hợp với chế độ xem này.",
          selectConversation:
            "Chọn một cuộc trò chuyện để xem ngữ cảnh ứng tuyển.",
          readOnlyOversight: "Giám sát chỉ đọc",
          assignedRecruiter: "Nhà tuyển dụng được phân công",
          saveAssignment: "Lưu phân công",
          conversationStarted: "Bắt đầu cuộc trò chuyện",
          messageFrom: (name: string) => `Tin nhắn từ ${name}`,
          noMessages:
            "Chưa có tin nhắn. Hãy tập trung cuộc trò chuyện vào hồ sơ ứng tuyển này.",
          message: "Tin nhắn",
          writeMessage: "Viết tin nhắn…",
          readOnlyConversation: "Cuộc trò chuyện ở chế độ chỉ đọc",
          sendHint: "Nhấn Enter để gửi · Shift + Enter để xuống dòng",
          sending: "Đang gửi…",
          send: "Gửi",
          ownerReadOnly:
            "Giám sát của chủ sở hữu ở chế độ chỉ đọc. Tin nhắn và trạng thái đã đọc không thay đổi.",
          candidateApplicationContext: "Ngữ cảnh ứng viên và hồ sơ ứng tuyển",
          backToApplication: "Quay lại hồ sơ ứng tuyển",
          applicationCommunication: "Trao đổi về hồ sơ ứng tuyển",
          recruitmentMessages: "Tin nhắn tuyển dụng",
          loadingConversation: "Đang tải cuộc trò chuyện bảo mật…",
          notAssigned:
            "Tin nhắn sẽ khả dụng khi công ty phân công nhà tuyển dụng cho hồ sơ của bạn.",
          unavailable: "Cuộc trò chuyện hiện không khả dụng.",
          chattingWith: (name: string, role: string) =>
            `Đang trò chuyện với ${name} (${role})`,
          applicationConversation: "Cuộc trò chuyện của hồ sơ ứng tuyển này",
          noMessagesShort: "Chưa có tin nhắn.",
          candidate: "Ứng viên",
          applicationStage: "Giai đoạn ứng tuyển",
          conversationOwner: "Người phụ trách cuộc trò chuyện",
          scopedNote:
            "Cuộc trò chuyện này thuộc về hồ sơ ứng tuyển của ứng viên.",
          errors: {
            loadConversations: "Không thể tải các cuộc trò chuyện tuyển dụng.",
            conversationUnavailable:
              "Cuộc trò chuyện tuyển dụng này không còn khả dụng.",
            loadAssignees: "Không thể tải danh sách người được phân công.",
            readOnly: "Tin nhắn ở chế độ chỉ đọc theo giai đoạn ứng tuyển này.",
            sendFailed: "Không thể gửi tin nhắn.",
            assignmentFailed: "Không thể lưu phân công.",
          },
          stages: {
            APPLIED: "Đã ứng tuyển",
            VIEWED: "Đã xem",
            SHORTLISTED: "Vào danh sách rút gọn",
            INTERVIEWING: "Đang phỏng vấn",
            OFFERED: "Đã đề nghị",
            HIRED: "Đã tuyển",
            OFFER_DECLINED: "Từ chối đề nghị",
            REJECTED: "Đã từ chối",
            WAITLISTED: "Danh sách chờ",
          },
        },
      }
    : {
        company: "Company",
        allCompanies: "All companies",
        ownedByYou: "Owned by you",
        memberAccess: "Member access",
        settings: "COMPANY SETTINGS",
        teamSettings: "Company settings / Team",
        yourCompanies: "Your companies",
        switchCompanyHint:
          "Switch the company profile and team context shown below.",
        addOrJoinCompany: "Add or join a company",
        ownershipLimitReached: (max: number) =>
          `Ownership limit reached (${max}/${max}). You can still join companies as a Recruiter or HR Manager.`,
        ownershipUsage: (count: number, max: number) =>
          `You own ${count}/${max} companies. Joining a company as a Recruiter or HR Manager does not use an ownership slot.`,
        manageCompanyHint:
          "You can manage the profile, team, and company settings.",
        invitedCompanyHint:
          "Companies that invited you as a recruiter or manager.",
        slots: (count: number, max: number) => `${count}/${max} slots`,
        linked: (count: number) => `${count} linked`,
        noOwnedCompany: "You do not own a company yet.",
        noOtherCompany: "No other company access yet.",
        noCompanyTitle: "No company is linked yet",
        noCompanyDescription:
          "Complete recruiter verification first. After approval, this screen will be linked to the company you are authorized to manage.",
        createCompany: "Create a Company",
        keepIdentityUpToDate:
          "Keep the company identity used by your job postings and candidate-facing cards up to date.",
        verification: "Verification",
        verificationStatus: {
          approved: "Approved",
          rejected: "Rejected",
          pending: "Pending",
        },
        verifiedIdentity: "Verified identity",
        companyName: "Company name",
        taxCode: "Tax code",
        locked: "Locked",
        lockedIdentityNote:
          "These details are locked after verification and cannot be edited here.",
        requestSupportChange: "Request a change through Support →",
        postingGate: "Posting gate",
        completeProfileBeforePosting:
          "Complete your company profile before posting a job",
        postingGateDescription:
          "The Create job posting action stays locked until these fields are complete.",
        requiredField: "Required field",
        logoRequired: "A company logo is required before a job can be posted.",
        fieldsRequired: "Fields marked * are required.",
        industry: "Industry",
        companySize: "Company size",
        address: "Address",
        website: "Website",
        logo: "Company logo",
        logoPreview: "Company logo preview",
        logoHint: "PNG, JPEG, or WebP. The image is resized before upload.",
        industryPlaceholder: "e.g. Information Technology",
        sizePlaceholder: "e.g. 200–500 employees",
        addressPlaceholder: "Street, district, city",
        description: "Description",
        savedProfile: "Saved company profile",
        publicCompanyInfo: "Your public company information",
        saved: "Saved",
        notProvided: "Not provided",
        readOnlyNote: "Your saved details are currently read-only.",
        ownership: "Ownership",
        authorizedRecruiters: "Authorized recruiters",
        ownershipDescription:
          "Only the owner and listed members can manage this company's job postings.",
        authorizedOwner: "Authorized owner",
        unclaimed: "Unclaimed",
        members: "Members",
        manageTeam: "Manage team",
        activeOwnerOnly:
          "Only the active company owner can manage team members.",
        dangerZone: "Danger zone",
        dangerDescription:
          "Permanently delete this company and all of its jobs, applications, messages, and analytics. This cannot be undone.",
        deleteDialogDescription:
          "This permanently removes the company and its recruiter data, including job postings, applications, messages, and analytics.",
        closeDeleteDialog: "Close delete dialog",
        typeToConfirm: "to confirm",
        cancel: "Cancel",
        removeLogo: "Remove logo",
        chooseAnotherLogo: "Choose another logo",
        preparingLogo: "Preparing logo…",
        chooseLogo: "Choose logo",
        saveProfile: "Save company profile",
        saving: "Saving…",
        editProfile: "Edit company profile",
        deleteCompany: "Delete company",
        deleteCompanyTitle: "Delete this company?",
        deleteCompanyDescription:
          "This action cannot be undone. Enter the exact company name to confirm.",
        deleteConfirmation: (name: string) => `Type “${name}” to confirm`,
        keepCompany: "Keep company",
        confirmDelete: "Confirm delete",
        deleting: "Deleting…",
        profileSaved: "Company profile saved.",
        logoReady: "Logo preview ready. Save the profile to upload it.",
        saveRequiredFields:
          "Complete the required company profile fields before saving.",
        unableToSave: "Unable to save company settings.",
        companyDeleted: "Company deleted.",
        unableToDelete: "Unable to delete company.",
        chooseValidImage: "Choose a valid image file.",
        role: {
          owner: "Owner",
          recruiter: "Recruiter",
          hrManager: "HR Manager",
          hiringManager: "Hiring manager",
          authorizedRecruiter: "Authorized recruiter",
          member: "Authorized recruiter/member",
        },
        team: {
          title: "Build your hiring team",
          description:
            "Invite trusted colleagues and manage their access to this company.",
          members: "Team members",
          memberCount: (count: number) => `${count} team members`,
          invite: "Invite a teammate",
          inviteDescription:
            "They must already have a SmartHire account to accept.",
          workEmail: "Work email",
          sendInvitation: "Send invitation",
          sending: "Sending…",
          manageMembers: "Manage roles and access for your company.",
          total: (count: number) => `${count} total`,
          makeRole: (role: string) => `Make ${role}`,
          restore: "Restore",
          suspend: "Suspend",
          remove: "Remove",
          primaryOwner: "Primary owner",
          pendingInvitations: "Pending invitations",
          statuses: {
            ACTIVE: "Active",
            SUSPENDED: "Suspended",
            REMOVED: "Removed",
          },
          pendingCount: (count: number) => `${count} pending`,
          pendingDescription: "People who have not yet joined your company.",
          invitedAs: (role: string, date: string) =>
            `Invited as ${role} · expires ${date}`,
          revoke: "Revoke",
          noPending: "No pending invitations",
          noPendingDescription:
            "Use the form above to invite your first teammate.",
          activity: "Team activity",
          activityDescription:
            "A recent, immutable record of team access changes.",
          recent: (count: number) => `${count} recent`,
          noActivity: "No activity yet",
          noActivityDescription:
            "Invitation and member-access actions will appear here.",
          roleChanged: "Role:",
          activityUpdated: "updated",
          system: "System",
          actions: {
            invited: "invited",
            accepted: "accepted",
            declined: "declined",
            revoked: "revoked",
            changedTheRoleOf: "changed the role of",
            suspended: "suspended",
            restored: "restored",
            removed: "removed",
          },
          invitationQueued: "Invitation queued for delivery",
          invitationQueuedDescription:
            "The recipient can review and respond from their SmartHire email.",
          invitationNotSent: "Invitation was not sent",
          memberUpdated: "Member access updated.",
          invitationRevoked: "Invitation revoked.",
          revokeConfirm:
            "Revoke this pending invitation? The recipient will no longer be able to join.",
          removeConfirm: (name: string) => `Remove ${name} from the company?`,
          invitationExists:
            "This email already has a pending invitation. Revoke it before sending a new one.",
          membershipExists: "This account is already a member of your company.",
          recipientUnavailable:
            "No active SmartHire account is available for this email.",
          inviteFailed: "Unable to send this invitation. Please try again.",
          updateFailed: "Unable to update this member.",
          revokeFailed: "Unable to revoke this invitation.",
        },
        jobManagement: {
          jobPostings: "Job postings",
          subtitle:
            "Manage every opening from first draft to a confident close.",
          create: "Create job posting",
          yourOpenings: "YOUR OPENINGS",
          trackPipeline: "Track your hiring pipeline",
          liveApplicantCounts: "Live applicant counts",
          overview: "Job posting overview",
          stats: {
            active: "Active jobs",
            applicants: "Total applicants",
            pending: "Pending approval",
            closing: "Closing soon",
          },
          tabs: {
            active: "Active",
            draft: "Drafts",
            pending_approval: "Pending approval",
            closed: "Closed",
          },
          searchPostings: "Search postings",
          searchPlaceholder: "Search by title or department",
          department: "Department",
          allDepartments: "All departments",
          skills: "Skills",
          arrangements: {
            ONSITE: "On-site",
            HYBRID: "Hybrid",
            REMOTE: "Remote",
          },
          statuses: {
            active: "Active",
            draft: "Draft",
            pending_approval: "Pending approval",
            closed: "Closed",
            rejected: "Rejected",
          },
          reasonLabels: {
            INCOMPLETE_OR_UNCLEAR: "Incomplete or unclear information",
            MISLEADING_CONTENT: "Misleading content",
            INAPPROPRIATE_LANGUAGE: "Inappropriate language",
            DUPLICATE_POSTING: "Duplicate posting",
            INVALID_REQUIREMENTS: "Invalid requirements",
            INSUFFICIENT_COMPENSATION: "Insufficient compensation details",
            VERIFICATION_MISMATCH: "Verification mismatch",
            PROHIBITED_CONTENT: "Prohibited content",
            OTHER: "Other reason",
          },
          updated: (value: string) => `Updated ${value}`,
          today: "today",
          dayAgo: "1 day ago",
          daysAgo: (count: number) => `${count} days ago`,
          monthAgo: "1 month ago",
          monthsAgo: (count: number) => `${count} months ago`,
          locationNotSet: "Location not set",
          noDepartment: "No department",
          untitled: "Untitled job posting",
          applicants: "Applicants",
          applicantsFor: (count: number, title: string) =>
            `${count} Applicants for ${title}`,
          viewPipeline: "View pipeline",
          viewPipelineFor: (title: string) => `View pipeline for ${title}`,
          reviseRejectedFor: (title: string) =>
            `Revise rejected job posting: ${title}`,
          viewUnderReviewFor: (title: string) =>
            `View job posting under review: ${title}`,
          viewClosedFor: (title: string) => `View closed job posting: ${title}`,
          editFor: (title: string) => `Edit job posting: ${title}`,
          revisePosting: "Revise posting",
          viewPosting: "View posting",
          editPosting: "Edit posting",
          deleteJob: "Delete job",
          extendDeadline: "Extend deadline",
          closeEarly: "Close early",
          deleteDraft: "Delete draft",
          withdrawToDraft: "Withdraw to draft",
          reactivate: "Reactivate job",
          reviewVersion: (sequence: number, state: string) =>
            `Review version ${sequence}: ${state}`,
          reviewLocked:
            " — This submitted version is locked while an Administrator reviews it.",
          reviewStates: {
            APPROVED: "Approved",
            REJECTED: "Rejected",
            PENDING: "Pending approval",
            UNDER_REVIEW: "Under review",
          },
          rejectionFeedback: "Rejection feedback",
          correctionRequest: "Administrator requested changes",
          reviseAndResubmit:
            "Revise the posting and submit again to request a new review.",
          approvedClosed:
            "This approved job post is closed and no longer accepting applications.",
          approvedVisible:
            "This job post has been approved and is visible to candidates.",
          correctionGuidance:
            "Your approved version remains live while you revise and submit a new version for review.",
          companySetupRequired: "Company setup required",
          companySetupDescription:
            "Link a recruiter-owned company before creating job postings. For local mock data, the company ownerUserId must match the signed-in user ID.",
          setupCompany: "Set up company",
          profileActionRequired: "Action required",
          completeProfile: "Complete company profile before posting",
          profileLocked:
            "Create job posting is locked until the following fields are complete.",
          openCompanySettings: "Open company settings",
          createFirst: "Create your first job posting",
          createNext: "Create a job posting",
          empty: {
            active: [
              "No active job postings",
              "Approved roles will appear here once they are ready for candidates.",
            ],
            draft: [
              "No drafts yet",
              "Start with a structured posting and save it when you are ready to continue.",
            ],
            pending_approval: [
              "Nothing waiting for review",
              "Submitted postings stay here until an admin approves or requests changes.",
            ],
            closed: [
              "No closed postings",
              "Roles closed manually or after their application window remain here for reference.",
            ],
            first: [
              "Create your first job posting",
              "Turn your next hiring need into a structured, candidate-ready opportunity.",
            ],
          },
          confirm: {
            closeTitle: "Close job early?",
            reactivateTitle: "Reactivate job?",
            withdrawTitle: "Withdraw submission?",
            deleteActiveTitle: "Delete active job?",
            deleteDraftTitle: "Delete draft?",
            closeLabel: "Close job",
            reactivateLabel: "Reactivate job",
            withdrawLabel: "Withdraw to Drafts",
            deleteActiveLabel: "Delete active job",
            deleteDraftLabel: "Delete draft",
            closeDescription:
              "This posting will stop accepting new applications and move to Closed. Existing applications will remain available in your recruitment pipeline.",
            reactivateDescription:
              "This posting will start accepting new applications again and move back to Active.",
            withdrawDescription:
              "The submission will leave the administrator review queue and return to Drafts. You can edit and submit it again later.",
            deleteActiveDescription:
              "This job will be removed from the public job data and candidate search immediately. Existing applications and audit history will be preserved.",
            deleteDraftDescription:
              "This draft will be permanently removed from the draft data. This action cannot be undone.",
            cancel: "Cancel",
            processing: "Processing…",
          },
          errors: {
            load: "Unable to load job postings.",
            close: "Unable to close this posting right now. Please try again.",
            reactivate:
              "Unable to reactivate this posting right now. Please try again.",
            delete:
              "Unable to delete this posting right now. Please try again.",
            withdraw:
              "Unable to withdraw this posting right now. Please try again.",
          },
        },
        navigation: {
          workspace: "Recruiter workspace",
          overview: "Overview",
          jobs: "Job postings",
          candidates: "Candidates",
          pipeline: "Pipeline",
          messages: "Recruitment messages",
          settings: "Company settings",
          soon: "Soon",
          signingOut: "Signing out…",
          signOut: "Sign out",
        },
        route: {
          jobPostings: "Job postings",
          loadingJobPostings: "Loading job postings",
          loadingJobPostingsDescription:
            "Loading your openings and hiring activity.",
          jobNotFound: "Job posting not found",
          jobNotFoundDescription:
            "This posting may have been removed or is no longer available.",
          backToPostings: "Back to job postings",
        },
        filter: {
          ownedByYou: "Owned by you",
          memberAccess: "Member access",
        },
        messages: {
          ownerOversight: "Owner oversight",
          recruiterWorkspace: "Recruiter workspace",
          oversightTitle: "Recruitment message oversight",
          title: "Recruitment messages",
          description:
            "Every conversation is scoped to one candidate application and one job.",
          conversations: "Recruitment conversations",
          searchCandidateOrJob: "Search candidate or job",
          searchPlaceholder: "Search messages",
          allCompanies: "All companies",
          jobPosting: "Job posting",
          allJobPostings: "All job postings",
          assignment: "Assignment",
          assignedToMe: "Assigned to me",
          unassigned: "Unassigned",
          allCompanyThreads: "All company threads",
          unread: (count: number) => `${count} unread`,
          noMatching: "No conversations match this view.",
          selectConversation:
            "Select a conversation to see its application context.",
          readOnlyOversight: "Read-only oversight",
          assignedRecruiter: "Assigned recruiter",
          saveAssignment: "Save assignment",
          conversationStarted: "Conversation started",
          messageFrom: (name: string) => `Message from ${name}`,
          noMessages:
            "No messages yet. Keep the conversation focused on this application.",
          message: "Message",
          writeMessage: "Write a message...",
          readOnlyConversation: "This conversation is read-only",
          sendHint: "Enter to send · Shift + Enter for a new line",
          sending: "Sending…",
          send: "Send",
          ownerReadOnly:
            "Owner oversight is read-only. Messages and read state are unchanged.",
          candidateApplicationContext: "Candidate and application context",
          backToApplication: "Back to application",
          applicationCommunication: "Application communication",
          recruitmentMessages: "Recruitment messages",
          loadingConversation: "Loading secure conversation…",
          notAssigned:
            "Messaging will be available when the company assigns a recruiter to your application.",
          unavailable: "This conversation is unavailable right now.",
          chattingWith: (name: string, role: string) =>
            `Chatting with ${name} (${role})`,
          applicationConversation: "Conversation for this application",
          noMessagesShort: "No messages yet.",
          candidate: "Candidate",
          applicationStage: "Application stage",
          conversationOwner: "Conversation owner",
          scopedNote:
            "This conversation is scoped to this candidate's application.",
          errors: {
            loadConversations: "Could not load recruitment conversations.",
            conversationUnavailable:
              "This recruitment conversation is no longer available.",
            loadAssignees: "Could not load eligible assignees.",
            readOnly: "Messaging is read-only for this application stage.",
            sendFailed: "Message could not be sent.",
            assignmentFailed: "Assignment could not be saved.",
          },
          stages: {
            APPLIED: "Applied",
            VIEWED: "Viewed",
            SHORTLISTED: "Shortlisted",
            INTERVIEWING: "Interviewing",
            OFFERED: "Offered",
            HIRED: "Hired",
            OFFER_DECLINED: "Offer declined",
            REJECTED: "Rejected",
            WAITLISTED: "Waitlisted",
          },
        },
      };
}

export type RecruiterWorkspaceCopy = ReturnType<typeof recruiterWorkspaceCopy>;
