DatabaseDirectory /var/lib/clamav
DatabaseOwner clamav
DatabaseMirror database.clamav.net
ScriptedUpdates yes
Checks 12
LogTime yes
Foreground yes
ConnectTimeout 30
ReceiveTimeout 60
TestDatabases yes
