export type JobLocale = "vi" | "en";

export function jobCopy(locale: JobLocale) {
  return locale === "vi"
    ? {
        employmentTypeLabels: {
          FULL_TIME: "Toàn thời gian",
          PART_TIME: "Bán thời gian",
          CONTRACT: "Hợp đồng",
          INTERNSHIP: "Thực tập",
          TEMPORARY: "Tạm thời",
        },
        experienceLevelLabels: {
          ENTRY: "Mới vào nghề",
          JUNIOR: "Sơ cấp",
          MID: "Trung cấp",
          SENIOR: "Cao cấp",
          LEAD: "Trưởng nhóm",
          MANAGER: "Quản lý",
        },
        workArrangementLabels: {
          ONSITE: "Tại văn phòng",
          HYBRID: "Kết hợp",
          REMOTE: "Từ xa",
        },
        posted: "Đã đăng",
        updated: "Đã cập nhật",
        jobTags: "Nhãn việc làm",
        showMoreTags: (count: number) => `Hiển thị thêm ${count} thẻ`,
        apply: "Ứng tuyển",
        applyNow: "Ứng tuyển ngay",
        hideApplicationForm: "Ẩn biểu mẫu ứng tuyển",
        signInToApply: "Đăng nhập để ứng tuyển",
        applied: "Đã ứng tuyển",
        applicationsClosed: "Đã đóng nhận hồ sơ",
        applicationLimitReached:
          "Bạn đã đạt giới hạn số lần ứng tuyển cho vị trí này.",
        signInToSave: "Đăng nhập để lưu việc làm này",
        hideJob: "Ẩn việc làm",
        quickView: "Xem nhanh",
        jobActions: "Thao tác việc làm",
        closeQuickView: "Đóng chế độ xem nhanh",
        quickViewCounter: (current: number, total: number) =>
          `${current} trên ${total} việc làm`,
        verifiedCompany: "Công ty đã được xác minh",
        salary: "Mức lương",
        location: "Địa điểm",
        experience: "Kinh nghiệm",
        requiredSkills: "Kỹ năng cần có",
        noSkillsListed: "Chưa có kỹ năng được cung cấp",
        whyYouWillLoveIt: "Điểm nổi bật của công việc",
        viewFullJobDetails: "Xem toàn bộ chi tiết việc làm",
        save: "Lưu",
        quickViewNavigation: "Điều hướng xem nhanh",
        previousJob: "Việc làm trước",
        nextJob: "Việc làm tiếp theo",
        checkCvFitAria:
          "Kiểm tra mức độ phù hợp của CV ở chế độ riêng tư. Kết quả chỉ hiển thị với bạn và không được chia sẻ cho nhà tuyển dụng.",
        checkCvFit: "Kiểm tra độ phù hợp của CV",
        private: "Riêng tư",
        breadcrumb: "Đường dẫn",
        jobs: "Việc làm",
        allJobs: "Tất cả việc làm",
        active: "Đang tuyển",
        closed: "Đã đóng",
        expired: "Đã hết hạn",
        years: (value: number) => `${value}+ năm`,
        noExperienceRequired: "Không yêu cầu kinh nghiệm",
        applicationDeadline: "Hạn ứng tuyển",
        openUntilFilled: "Mở tuyển đến khi đủ ứng viên",
        jobContext: "Thông tin việc làm",
        relatedJobs: "Việc làm tương tự",
        keepExploring: "Tiếp tục khám phá",
        seeMoreJobs: "Xem thêm việc làm",
        noRelatedJobs: "Hiện chưa có vị trí tương tự phù hợp.",
        saveJob: "Lưu việc làm",
        removeSavedJob: "Bỏ lưu việc làm",
        saved: "Đã lưu",
        saving: "Đang lưu…",
        savingJob: "Đang lưu việc làm…",
        removing: "Đang bỏ lưu…",
        removingJob: "Đang bỏ lưu việc làm…",
        savedSuccess: "Đã lưu việc làm.",
        removedSuccess: "Đã bỏ lưu việc làm.",
        updateFailed: "Không thể cập nhật việc làm đã lưu. Vui lòng thử lại.",
        jobHidden: "Đã ẩn việc làm khỏi danh sách của bạn",
        jobHiddenDescription: "Bạn có thể hoàn tác trong 5 giây tiếp theo.",
        undo: "Hoàn tác",
        filterSaved: "Đã lưu bộ lọc",
        filterSavedDescription: (name: string) =>
          `“${name}” đã sẵn sàng để bạn sử dụng lại.`,
        newJob: "Mới",
        featuredJob: "Nổi bật",
        updatedAt: (value: string) => `Đã cập nhật ${value}`,
        notListed: "Chưa có thông tin",
        age: "Độ tuổi",
        educationLevel: "Trình độ học vấn",
        overview: "Tổng quan",
        overviewDescription:
          "Những thông tin cốt lõi trước khi bạn tìm hiểu sâu hơn về vai trò.",
        jobRequirementsAtAGlance: "Tổng quan yêu cầu công việc",
        specialization: "Chuyên môn",
        jobSpecialization: "Chuyên môn việc làm",
        roleFocus: "Trọng tâm công việc",
        roleFocusSkills: "Kỹ năng trọng tâm của công việc",
        keyResponsibilities: "Trách nhiệm chính",
        jobDescription: "Mô tả việc làm",
        jobDescriptionDescription:
          "Tổng quan rõ ràng về công việc, kỳ vọng và tác động bạn có thể tạo ra.",
        requirements: "Yêu cầu",
        requirementsDescription:
          "Những yếu tố giúp bạn hoàn thành tốt vai trò này.",
        benefits: "Quyền lợi",
        benefitsDescription:
          "Toàn bộ gói quyền lợi được trình bày đầy đủ để bạn dễ dàng so sánh.",
        mustHaveRequirements: "Yêu cầu bắt buộc",
        niceToHave: "Điểm cộng",
        noNiceToHave: "Chưa có thêm yêu cầu điểm cộng nào được cung cấp.",
        benefitsInterview:
          "Thông tin quyền lợi sẽ được trao đổi trong quá trình phỏng vấn.",
        jobDetails: "Chi tiết việc làm",
        jobDetailSections: "Các phần chi tiết việc làm",
        moreDetailsHiringTeam: "Đội ngũ tuyển dụng sẽ cung cấp thêm thông tin.",
        company: "Công ty",
        companyInfo: "Thông tin công ty",
        verifiedEmployer: "Nhà tuyển dụng đã được SmartHire xác minh",
        scale: "Quy mô",
        industry: "Ngành nghề",
        address: "Địa chỉ",
        visitCompanyWebsite: "Truy cập website công ty",
        atAGlance: "Tổng quan nhanh",
        generalInformation: "Thông tin chung",
        level: "Cấp độ",
        education: "Học vấn",
        numberOfHires: "Số lượng cần tuyển",
        positions: (count: number) => `${count} vị trí`,
        workArrangement: "Hình thức làm việc",
        employmentType: "Loại hình công việc",
        exploreMore: "Khám phá thêm",
        similarJobs: "Việc làm tương tự",
        similarJobsEmpty:
          "Việc làm tương tự sẽ xuất hiện khi có thêm vị trí phù hợp.",
        seeMore: "Xem thêm",
        safetyCheck: "Kiểm tra an toàn",
        reportJob: "Báo cáo việc làm",
        reportJobDescription:
          "Việc làm này có vẻ không ổn hoặc đáng ngờ? Hãy cho đội ngũ biết để chúng tôi xem xét.",
        reportDescription:
          "Báo cáo của bạn là riêng tư và sẽ được kiểm duyệt bởi người có thẩm quyền. Báo cáo không tự động gỡ việc làm.",
        reportReasons: {
          FRAUD: "Lừa đảo hoặc gian dối",
          MISLEADING: "Thông tin gây hiểu lầm",
          DUPLICATE: "Tin đăng trùng lặp",
          DISCRIMINATORY: "Nội dung phân biệt đối xử",
          INAPPROPRIATE: "Nội dung không phù hợp",
          OTHER: "Lý do khác",
        },
        reason: "Lý do",
        selectReason: "Chọn một lý do",
        details: "Chi tiết",
        required: "(bắt buộc)",
        optional: "(không bắt buộc)",
        reportPrivacyHint:
          "Không đưa mật khẩu, nội dung CV hoặc dữ liệu cá nhân không cần thiết vào báo cáo.",
        reviewReportFields: "Vui lòng kiểm tra các trường báo cáo.",
        submittingReport: "Đang gửi báo cáo…",
        submitReport: "Gửi báo cáo",
        cancel: "Hủy",
        reportFailed: "Không thể gửi báo cáo. Vui lòng thử lại.",
        reportSubmitted: "Đã gửi báo cáo.",
        whySignal: "Tín hiệu từ SmartHire",
        whyWorkingHere: "Vì sao bạn sẽ yêu thích môi trường này",
        backToJobs: "Quay lại việc làm",
        roleWorthNextMove: "Một vai trò xứng đáng cho bước tiến tiếp theo",
        jobStatus: "Trạng thái việc làm",
        keyJobInformation: "Thông tin chính về việc làm",
        candidateWorkspace: "Không gian ứng viên",
        savedJobsTitle: "Việc làm đã lưu",
        savedJobsEmpty: "Bạn chưa lưu việc làm nào.",
        findJobs: "Tìm việc →",
        savedJobsDescription: "Theo dõi những cơ hội bạn muốn xem lại.",
        savedJobsAria: "Việc làm đã lưu",
        suggestedJobsTitle: "Việc làm đề xuất",
        suggestedJobsDescription:
          "Đề xuất dựa trên các tùy chọn, kỹ năng và kinh nghiệm bạn đã chia sẻ.",
        completePreferences: "Hoàn thiện tiêu chí tìm việc",
        completePreferencesDescription:
          "Cho biết vị trí mục tiêu, kỹ năng, kinh nghiệm và địa điểm để SmartHire đề xuất cơ hội phù hợp hơn.",
        updatePreferences: "Cập nhật tùy chọn",
        foundPrefix: "Tìm thấy",
        foundSuffix: "việc làm phù hợp với tùy chọn của bạn",
        suggestedJobsAria: "Việc làm đề xuất",
        noMatchingJobs:
          "Hiện chưa có việc làm phù hợp. Hãy thử mở rộng tùy chọn của bạn.",
        notQuiteRight: "Chưa đúng ý bạn?",
        recommendationsImprove:
          "Cập nhật tùy chọn để cải thiện các đề xuất trong tương lai.",
        matchingJobs: "Việc làm phù hợp",
        searchLoadError: "Không thể tải việc làm",
        searchResultsKicker: "Vị trí đang tuyển, thông tin rõ ràng",
        searchResultsDescription:
          "Hiển thị những cơ hội phù hợp nhất với bộ lọc hiện tại.",
        loadMoreJobs: "Tải thêm việc làm",
        clearFiltersRetry: "Xóa bộ lọc rồi thử lại",
        clearAllFilters: "Xóa tất cả bộ lọc",
        loadingJobs: "Đang tải cơ hội việc làm…",
        loadingJobsDescription:
          "Đang chuẩn bị các tin tuyển dụng đã xác minh và bộ lọc bạn chọn.",
        detailsLoadError: "Không thể tải chi tiết việc làm",
        tryAgainLater: "Vui lòng thử lại sau ít phút.",
        unavailableTitle: "Việc làm này không còn khả dụng",
        unavailableDescription:
          "Liên kết có thể đã cũ hoặc tin tuyển dụng không còn được công khai.",
        browseActiveJobs: "Xem các việc làm đang tuyển",
        maxApplicationsTitle: "Đã đạt số lần ứng tuyển tối đa",
        returnToFindJobs: "Quay lại Tìm việc",
        applicationsLoadError: "Không thể tải danh sách ứng tuyển",
        applicationsLoadErrorDescription:
          "Dữ liệu ứng tuyển của bạn vẫn an toàn. Hãy thử lại hoặc quay lại tìm việc.",
        tryAgain: "Thử lại",
        findJobsLabel: "Tìm việc",
      }
    : {
        employmentTypeLabels: {
          FULL_TIME: "Full time",
          PART_TIME: "Part time",
          CONTRACT: "Contract",
          INTERNSHIP: "Internship",
          TEMPORARY: "Temporary",
        },
        experienceLevelLabels: {
          ENTRY: "Entry level",
          JUNIOR: "Junior",
          MID: "Mid-level",
          SENIOR: "Senior",
          LEAD: "Lead",
          MANAGER: "Manager",
        },
        workArrangementLabels: {
          ONSITE: "On-site",
          HYBRID: "Hybrid",
          REMOTE: "Remote",
        },
        posted: "Posted",
        updated: "Updated",
        jobTags: "Job tags",
        showMoreTags: (count: number) => `Show ${count} more tags`,
        apply: "Apply",
        applyNow: "Apply now",
        hideApplicationForm: "Hide application form",
        signInToApply: "Sign in to apply",
        applied: "Applied",
        applicationsClosed: "Applications closed",
        applicationLimitReached:
          "You have reached the maximum number of applications for this job.",
        signInToSave: "Sign in to save this job",
        hideJob: "Hide job",
        quickView: "Quick view",
        jobActions: "Job actions",
        closeQuickView: "Close quick view",
        quickViewCounter: (current: number, total: number) =>
          `${current} of ${total} jobs`,
        verifiedCompany: "Verified company",
        salary: "Salary",
        location: "Location",
        experience: "Experience",
        requiredSkills: "Required skills",
        noSkillsListed: "Not listed",
        whyYouWillLoveIt: "Why you'll love it",
        viewFullJobDetails: "View full job details",
        save: "Save",
        quickViewNavigation: "Quick view navigation",
        previousJob: "Previous job",
        nextJob: "Next job",
        checkCvFitAria:
          "Check CV fit privately. Results are visible only to you and are not shared with recruiters.",
        checkCvFit: "Check CV fit privately",
        private: "Private",
        breadcrumb: "Breadcrumb",
        jobs: "Jobs",
        allJobs: "All jobs",
        active: "Active",
        closed: "Closed",
        expired: "Expired",
        years: (value: number) => `${value}+ years`,
        noExperienceRequired: "No experience required",
        applicationDeadline: "Application deadline",
        openUntilFilled: "Open until filled",
        jobContext: "Job context",
        relatedJobs: "Related jobs",
        keepExploring: "Keep exploring",
        seeMoreJobs: "See more jobs",
        noRelatedJobs: "No closely matched roles are available right now.",
        saveJob: "Save job",
        removeSavedJob: "Remove saved job",
        saved: "Saved",
        saving: "Saving…",
        savingJob: "Saving job…",
        removing: "Removing…",
        removingJob: "Removing saved job…",
        savedSuccess: "Job saved.",
        removedSuccess: "Job removed from saved jobs.",
        updateFailed: "Could not update this saved job. Try again.",
        jobHidden: "Job hidden from your list",
        jobHiddenDescription: "You can undo this for the next 5 seconds.",
        undo: "Undo",
        filterSaved: "Filter saved",
        filterSavedDescription: (name: string) =>
          `“${name}” is ready to reuse.`,
        newJob: "New",
        featuredJob: "Featured",
        updatedAt: (value: string) => `Updated ${value}`,
        notListed: "Not listed",
        age: "Age",
        educationLevel: "Education level",
        overview: "Overview",
        overviewDescription:
          "The essentials at a glance before you dive into the role.",
        jobRequirementsAtAGlance: "Job requirements at a glance",
        specialization: "Specialization",
        jobSpecialization: "Job specialization",
        roleFocus: "Role focus",
        roleFocusSkills: "Role focus skills",
        keyResponsibilities: "Key responsibilities",
        jobDescription: "Job description",
        jobDescriptionDescription:
          "A clear view of the work, expectations, and impact you can make.",
        requirements: "Requirements",
        requirementsDescription:
          "The signals that will help you do well in this role.",
        benefits: "Benefits",
        benefitsDescription:
          "The full package, kept together so you can compare with confidence.",
        mustHaveRequirements: "Must-have requirements",
        niceToHave: "Nice-to-have",
        noNiceToHave: "No additional nice-to-have requirements were provided.",
        benefitsInterview:
          "Benefits details will be shared during the interview process.",
        jobDetails: "Job details",
        jobDetailSections: "Job detail sections",
        moreDetailsHiringTeam:
          "More details will be shared by the hiring team.",
        company: "Company",
        companyInfo: "Company info",
        verifiedEmployer: "Verified SmartHire employer",
        scale: "Scale",
        industry: "Industry",
        address: "Address",
        visitCompanyWebsite: "Visit company website",
        atAGlance: "At a glance",
        generalInformation: "General information",
        level: "Level",
        education: "Education",
        numberOfHires: "Number of hires",
        positions: (count: number) =>
          `${count} position${count === 1 ? "" : "s"}`,
        workArrangement: "Work arrangement",
        employmentType: "Employment type",
        exploreMore: "Explore more",
        similarJobs: "Similar jobs",
        similarJobsEmpty:
          "Similar jobs will appear here as more roles become available.",
        seeMore: "See more",
        safetyCheck: "Safety check",
        reportJob: "Report this job",
        reportJobDescription:
          "This job seems off or suspicious? Let our team know so we can review it.",
        reportDescription:
          "Your report is private and reviewed by authorized moderators. It does not automatically remove the job.",
        reportReasons: {
          FRAUD: "Fraud or scam",
          MISLEADING: "Misleading information",
          DUPLICATE: "Duplicate posting",
          DISCRIMINATORY: "Discriminatory content",
          INAPPROPRIATE: "Inappropriate content",
          OTHER: "Other concern",
        },
        reason: "Reason",
        selectReason: "Select a reason",
        details: "Details",
        required: "(required)",
        optional: "(optional)",
        reportPrivacyHint:
          "Do not include passwords, CV content, or unnecessary personal data.",
        reviewReportFields: "Review the report fields.",
        submittingReport: "Submitting report…",
        submitReport: "Submit report",
        cancel: "Cancel",
        reportFailed: "Could not submit this report. Try again.",
        reportSubmitted: "Report submitted.",
        whySignal: "The Smart Hire signal",
        whyWorkingHere: "Why you'll love working here",
        backToJobs: "Back to jobs",
        roleWorthNextMove: "A role worth your next move",
        jobStatus: "Job status",
        keyJobInformation: "Key job information",
        candidateWorkspace: "Candidate workspace",
        savedJobsTitle: "Saved Jobs",
        savedJobsEmpty: "You have not saved any jobs yet.",
        findJobs: "Find jobs →",
        savedJobsDescription:
          "Keep track of opportunities you want to revisit.",
        savedJobsAria: "Saved jobs",
        suggestedJobsTitle: "Suggested Jobs",
        suggestedJobsDescription:
          "Recommendations are based on the preferences, skills, and experience you have shared.",
        completePreferences: "Complete your job preferences",
        completePreferencesDescription:
          "Share your target position, skills, experience, and location so SmartHire can recommend better opportunities.",
        updatePreferences: "Update preferences",
        foundPrefix: "Found",
        foundSuffix: "jobs that match your preferences",
        suggestedJobsAria: "Suggested jobs",
        noMatchingJobs:
          "No matching jobs are available right now. Try broadening your preferences.",
        notQuiteRight: "Not quite right?",
        recommendationsImprove:
          "Update your preferences to improve future recommendations.",
        matchingJobs: "Matching jobs",
        searchLoadError: "Jobs could not be loaded",
        searchResultsKicker: "Open roles, clear signal",
        searchResultsDescription:
          "Showing the strongest opportunities for this view.",
        loadMoreJobs: "Load more jobs",
        clearFiltersRetry: "Clear filters and retry",
        clearAllFilters: "Clear all filters",
        loadingJobs: "Loading job opportunities…",
        loadingJobsDescription:
          "Preparing verified listings and your selected filters.",
        detailsLoadError: "Job details could not be loaded",
        tryAgainLater: "Try again in a moment.",
        unavailableTitle: "This job is not available",
        unavailableDescription:
          "The link may be outdated, or the posting is not publicly available.",
        browseActiveJobs: "Browse active jobs",
        maxApplicationsTitle: "Maximum applications reached",
        returnToFindJobs: "Return to Find Jobs",
        applicationsLoadError: "We couldn’t load your applications",
        applicationsLoadErrorDescription:
          "Your application data is still safe. Try again or return to the job search.",
        tryAgain: "Try again",
        findJobsLabel: "Find jobs",
      };
}

export function jobExperienceLabel(value: string, locale: JobLocale) {
  return jobAttributeLabel(value, locale);
}

export function jobAttributeLabel(value: string, locale: JobLocale) {
  const copy = jobCopy(locale);
  const labels = [
    copy.employmentTypeLabels,
    copy.experienceLevelLabels,
    copy.workArrangementLabels,
  ] as Array<Record<string, string>>;
  for (const labelSet of labels) {
    const label = labelSet[value];
    if (label) return label;
  }
  return locale === "vi"
    ? copy.notListed
    : value
        .replaceAll("_", " ")
        .toLowerCase()
        .replace(/\b\w/gu, (letter) => letter.toUpperCase());
}
