-- RenameIndex
ALTER INDEX "FullAccountRecoveryOperation_cancellationNotificationIdempotenc" RENAME TO "FullAccountRecoveryOperation_cancellationNotificationIdempo_key";

-- RenameIndex
ALTER INDEX "FullAccountRecoveryOperation_cancellationNotificationOutboxId_k" RENAME TO "FullAccountRecoveryOperation_cancellationNotificationOutbox_key";

-- RenameIndex
ALTER INDEX "FullAccountRecoveryOperation_completionNotificationIdempotencyK" RENAME TO "FullAccountRecoveryOperation_completionNotificationIdempote_key";

-- RenameIndex
ALTER INDEX "FullAccountRecoveryOperation_pendingNotificationIdempotencyKey_" RENAME TO "FullAccountRecoveryOperation_pendingNotificationIdempotency_key";
