ALTER TYPE "EmailKind" ADD VALUE IF NOT EXISTS 'COMPANY_INVITATION';
ALTER TYPE "InAppNotificationKind" ADD VALUE IF NOT EXISTS 'COMPANY_INVITATION_RECEIVED';
ALTER TYPE "InAppNotificationContextType" ADD VALUE IF NOT EXISTS 'COMPANY_INVITATION';
