"use client";

import type { AiAssessment, AutomaticMatch, FinalScore, ScoringState } from "@/shared/contracts/scoring";

export function AiAssessmentTab({ state, onRetry }: { state: ScoringState; onRetry: () => void }) {
  if (state.kind === "PENDING") return <RetryingAssessment automatic={state.automaticMatch} />;
  if (state.kind === "PROCESSING") return <div className="ai-ranking-retry-state" role="status"><div className="ai-ranking-status-icon" aria-hidden="true">{String.fromCharCode(8635)}</div><h3>AI assessment is processing</h3><p>The deterministic result will stay visible while the initial scoring operation runs in the background.</p><button type="button" className="ai-ranking-button ai-ranking-button--loading" disabled><span aria-hidden="true">...</span> Processing...</button></div>;
  if (state.kind === "NOT_CALCULATED") return <div className="ai-ranking-empty-panel"><span aria-hidden="true">{String.fromCharCode(8212)}</span><h3>AI assessment is not calculated</h3><p>There is no published deterministic result to send for AI assessment yet.</p></div>;
  if (state.kind === "UNAVAILABLE") return <UnavailableAssessment automatic={state.automaticMatch} failures={state.consecutiveFailures} onRetry={onRetry} />;
  return <ReadyAssessment automatic={state.automaticMatch} ai={state.aiAssessment} finalScore={state.finalScore} />;
}

function RetryingAssessment({ automatic }: { automatic: AutomaticMatch | null }) {
  return <div className="ai-ranking-tab-content"><div className="ai-ranking-progress-banner" role="status"><span aria-hidden="true">{String.fromCharCode(8635)}</span><div><strong>Retrying AI evaluation</strong><p>The {automatic?.score ?? "deterministic"}/100 deterministic result stays visible while AI runs in the background.</p></div><button type="button" className="ai-ranking-button ai-ranking-button--loading" disabled><span aria-hidden="true">...</span> Retrying...</button></div><div className="ai-ranking-score-cards"><article><span>Automatic match</span><strong>{automatic ? automatic.score + "/100" : "Ready"}</strong><small>Deterministic result preserved</small></article><article><span>AI assessment</span><strong>Processing</strong><small>Retry in progress</small></article><article><span>Final score</span><strong>Pending</strong><small>Will update when AI succeeds</small></article></div><div className="ai-ranking-formula-row"><strong>Deterministic {automatic?.score ?? "match"} ready - AI retry in progress</strong><span>{automatic ? "JD " + automatic.jdVersion + " - CV " + automatic.cvVersion + " - Config " + automatic.configVersion : "Lineage is preserved"}</span></div></div>;
}

function UnavailableAssessment({ automatic, failures, onRetry }: { automatic: AutomaticMatch; failures: number; onRetry: () => void }) {
  return <div className="ai-ranking-tab-content"><div className="ai-ranking-warning ai-ranking-warning--amber" role="alert"><span aria-hidden="true">!</span><div><strong>AI evaluation is unavailable</strong><p>Deterministic matching is complete. No hybrid final score is shown until AI succeeds.</p></div><button type="button" className="ai-ranking-button" onClick={onRetry}>Retry AI evaluation</button></div><div className="ai-ranking-score-cards"><article><span>Automatic match</span><strong>{automatic.score}/100</strong><small>Ready</small></article><article><span>AI assessment</span><strong>Unavailable</strong><small>Retryable state</small></article><article><span>Final score</span><strong>Not calculated</strong><small>AI is not substituted with zero</small></article></div><div className="ai-ranking-formula-row"><strong>Deterministic match: {automatic.score}/100 - AI unavailable</strong><span>JD {automatic.jdVersion} - CV {automatic.cvVersion} - Config {automatic.configVersion}</span></div>{failures >= 3 ? <div className="ai-ranking-support-callout" role="status">Repeated AI failure - try later or contact support.</div> : null}<p className="ai-ranking-muted">The full Automatic match tab remains available, including required skills, experience, and CV evidence.</p></div>;
}

function ReadyAssessment({ automatic, ai, finalScore }: { automatic: AutomaticMatch; ai: AiAssessment; finalScore: FinalScore }) {
  const strengths = ai.findings.filter((item) => item.kind === "STRENGTH");
  const verify = ai.findings.filter((item) => item.kind === "POINT_TO_VERIFY");
  return <div className="ai-ranking-tab-content"><section className="ai-ranking-overall"><div className="ai-ranking-overall-icon" aria-hidden="true">AI</div><div><h3>Overall assessment <span>AI-generated</span></h3><p>{ai.overallSummary}</p></div></section><div className="ai-ranking-finding-grid"><FindingColumn title="Evidence-based strengths" icon={String.fromCharCode(9673)} items={strengths} tone="green" /><FindingColumn title="Points to verify" icon="!" items={verify} tone="yellow" /></div><section className="ai-ranking-ai-score"><div className="ai-ranking-ai-score-number"><strong>{ai.score}</strong><span>/ 100 AI points</span></div><div><h3>Why did the AI give a score of {ai.score}?</h3><ul>{ai.breakdown.map((line) => <li key={line}>{line}</li>)}</ul></div></section><div className="ai-ranking-confidence-grid"><section className="ai-ranking-confidence"><div><strong>Confidence - {ai.modelVersion} - {ai.promptVersion}</strong><b>{ai.confidencePercent}% - {ai.confidenceLabel}</b></div><div className="ai-ranking-progress" role="progressbar" aria-valuenow={ai.confidencePercent} aria-valuemin={0} aria-valuemax={100}><span style={{ width: ai.confidencePercent + "%" }} /></div>{ai.confidenceLevel === "LOW" ? <p role="alert">Low confidence - assess the evidence carefully yourself.</p> : null}</section><div className="ai-ranking-compliance"><span aria-hidden="true">!</span>{ai.compliance.label}</div></div><section className="ai-ranking-questions"><h3>Suggested interview questions</h3>{ai.questions.kind === "GENERATED" ? <ol>{ai.questions.items.map((question, index) => <li key={question.pointToVerifyId + "-" + question.question}><span>{index + 1}</span>{question.question}</li>)}</ol> : <p>{ai.questions.fallbackMessage}</p>}</section><p className="ai-ranking-muted">Formula: {finalScore.formulaText} - Automatic {automatic.score} x 0.6 + AI {ai.score} x 0.4</p></div>;
}

function FindingColumn({ title, icon, items, tone }: { title: string; icon: string; items: AiAssessment["findings"]; tone: "green" | "yellow" }) {
  return <section className={"ai-ranking-findings ai-ranking-findings--" + tone}><h3><span aria-hidden="true">{icon}</span>{title}</h3>{items.length ? <ul>{items.map((item) => <li key={item.id}><strong>{item.title}</strong><span>{item.evidence}</span></li>)}</ul> : <p>No items returned.</p>}</section>;
}
