import type { WorkspaceLocale } from "@/frontend/features/dashboard/client/workspace-locale";

const stageLabels = {
  APPLIED: "New",
  VIEWED: "Viewed",
  SHORTLISTED: "Shortlisted",
  INTERVIEWING: "Interviewing",
  OFFERED: "Offered",
  HIRED: "Hired",
  OFFER_DECLINED: "Offer declined",
  REJECTED: "Rejected",
  WAITLISTED: "Waitlisted",
  WITHDRAWN: "Withdrawn",
} as const;

const rejectionReasons = {
  REQUIRED_TECHNICAL_EXPERIENCE_NOT_DEMONSTRATED:
    "Required technical experience not demonstrated",
  INSUFFICIENT_EXPERIENCE: "Insufficient experience",
  REQUIRED_SKILLS_NOT_DEMONSTRATED: "Required skills not demonstrated",
  POSITION_FILLED: "Position filled",
  APPLICATION_WITHDRAWN_BY_CANDIDATE: "Application withdrawn by candidate",
  OTHER_JOB_RELATED_REASON: "Other job-related reason",
} as const;

const priorityLabels = {
  HIGH: "High review priority",
  NORMAL: "Medium review priority",
  LOW: "Low review priority",
  HOLD: "Hold for later",
} as const;

export function applicationDetailCopy(locale: WorkspaceLocale) {
  if (locale === "vi") {
    return {
      stageLabels: {
        APPLIED: "Mới",
        VIEWED: "Đã xem",
        SHORTLISTED: "Danh sách rút gọn",
        INTERVIEWING: "Đang phỏng vấn",
        OFFERED: "Đã gửi đề nghị",
        HIRED: "Đã tuyển",
        OFFER_DECLINED: "Từ chối đề nghị",
        REJECTED: "Đã từ chối",
        WAITLISTED: "Danh sách chờ",
        WITHDRAWN: "Đã rút hồ sơ",
      },
      drawer: {
        applyingFor: (jobTitle: string) => `Ứng tuyển vào ${jobTitle}`,
        close: "Đóng chi tiết ứng viên",
        closeDialog: "Đóng hộp thoại",
        reviewInfo: "Xem thông tin ứng viên",
        recruitmentActions: "Thao tác tuyển dụng ứng viên",
        viewCv: "Xem CV",
        viewCoverLetter: "Xem thư xin việc",
        viewProfile: "Xem hồ sơ",
        shortlist: "Đưa vào danh sách rút gọn",
        shortlisting: "Đang đưa vào danh sách rút gọn…",
        openingChat: "Đang mở trò chuyện…",
        messageCandidate: "Nhắn tin cho ứng viên",
        moveToInterview: "Chuyển sang phỏng vấn",
        tabsLabel: "Chi tiết điểm ứng viên",
        automatic: "Đối sánh tự động",
        assessment: "Đánh giá AI",
        documents: "CV và thư xin việc",
        profile: "Hồ sơ",
        retry: "Thử lại",
        dismiss: "Bỏ qua",
        loadError: "Không thể tải phần giải thích điểm số.",
        retryError: "Không thể bắt đầu thử lại AI.",
        scoreError: "Không thể bắt đầu tính điểm ứng viên.",
        profileError: "Hồ sơ ứng viên chưa khả dụng.",
        scoringFailed: "Tính điểm CV thất bại",
        scoringStopped: (code: string) =>
          `Tác vụ đã dừng an toàn${code ? ` (${code})` : ""}. Hãy thử tính điểm lại sau khi xử lý vấn đề về CV hoặc nhà cung cấp.`,
        retryScoring: "Tính điểm lại",
        aiUnavailable: "Đánh giá AI chưa khả dụng",
        retryAi: "Thử lại đánh giá AI",
        aiRetrying: "Đã sẵn sàng theo quy tắc · đang thử lại AI",
        aiRetryingDescription: (score: number | string) =>
          `Kết quả ${score}/100 vẫn được hiển thị trong khi AI chạy nền.`,
        scoringInProgress: "Đang tính điểm",
        scoringInProgressDescription:
          "Kết quả một phần sẽ hiển thị ở đây mà không chặn danh sách ứng viên.",
        rescoring: "Đang tính điểm lại · kết quả hiện tại vẫn được hiển thị.",
        profileReview: "Xem xét hồ sơ ứng viên",
        currentProfile: "Hồ sơ ứng viên hiện tại",
        profileDescription:
          "Chi tiết hồ sơ phản ánh lựa chọn chia sẻ hiện tại của ứng viên.",
        noHeadline: "Chưa chia sẻ tiêu đề hồ sơ",
        noSummary: "Chưa chia sẻ tóm tắt hồ sơ",
        sharedSkills: "Kỹ năng đã chia sẻ",
        noSharedSections:
          "Hồ sơ hiện tại không có phần nào được chia sẻ với nhà tuyển dụng.",
        contactShared: "Ứng viên đã chia sẻ thông tin liên hệ cho đơn này.",
        contactNotShared: "Thông tin liên hệ chưa được chia sẻ cho đơn này.",
        humanDecision: "Quyết định của con người",
        scoreUnchanged: "Điểm số không thay đổi",
        editPriority: "Sửa mức ưu tiên",
        setPriority: "Đặt mức ưu tiên",
        reject: "Từ chối",
        assessmentView: "Chế độ xem đánh giá",
        pending: "Đang chờ",
        processing: "Đang xử lý",
        retryingAi: "Đang thử lại AI",
        ruleBasedOnly: "Chỉ dùng quy tắc",
        scoringFailedLabel: "Tính điểm thất bại",
        notCalculated: "Chưa tính điểm",
        hybridUnavailable: "Điểm kết hợp chưa khả dụng",
        scoringJobFailed: "Tác vụ tính điểm thất bại",
        hybridPending: "Điểm kết hợp đang chờ",
        finalScore: "Điểm cuối",
        aiLabel: (label: string) => `AI: ${label}`,
        aiUnavailableMessage: (code: string) => {
          if (code === "AI_PROVIDER_INVALID_REQUEST")
            return "Nhà cung cấp AI từ chối yêu cầu đánh giá. Hãy kiểm tra cấu hình nhà cung cấp hoặc mô hình trước khi thử lại.";
          if (code === "AI_PROVIDER_MODEL_NOT_FOUND")
            return "Mô hình AI đã cấu hình chưa khả dụng. Hãy cập nhật cấu hình mô hình trước khi thử lại.";
          if (code === "AI_PROVIDER_AUTHENTICATION")
            return "Xác thực nhà cung cấp AI thất bại. Hãy kiểm tra khóa API trên máy chủ trước khi thử lại.";
          if (code === "AI_PROVIDER_POLICY_NOT_APPROVED")
            return "Tính điểm AI đang bị tắt theo cấu hình quyền riêng tư hoặc môi trường phát triển hiện tại.";
          if (code === "AI_PROVIDER_NOT_CONFIGURED")
            return "Nhà cung cấp AI chưa được cấu hình. Hãy thêm thiết lập nhà cung cấp đã được phê duyệt trước khi thử lại.";
          if (code === "AI_PROVIDER_MALFORMED")
            return "Nhà cung cấp AI trả về đánh giá không hợp lệ sau các lần thử tự động. Hãy thử lại đánh giá AI; không cần khởi động lại worker.";
          return "Đối sánh theo quy tắc đã hoàn tất. Điểm theo quy tắc và bằng chứng CV vẫn hiển thị trong khi nhà cung cấp AI chưa khả dụng.";
        },
        retryDialogTitle: "Thử lại đánh giá AI?",
        retryDialogSubtitle: (name: string) => `${name} · Chỉ thử lại AI`,
        retryDialogInfo:
          "Kết quả theo quy tắc vẫn hiển thị và không được tính lại. Lần thử lại này được ghi nhận là thao tác của nhà tuyển dụng.",
        scoreDialogTitle: (label: string) => `${label}?`,
        scoreDialogSubtitle: (name: string) => `${name} · một đơn ứng tuyển`,
        scoreDialogInfo:
          "Chỉ ứng viên này được đưa vào hàng đợi. Điểm số và đánh giá sẽ cập nhật tại đây khi worker chạy nền hoàn tất.",
      },
      automatic: {
        lineagePreserved: "Đã bảo toàn nguồn gốc dữ liệu",
        scoreInputs: "Đầu vào điểm số",
        config: "Cấu hình",
        noneDetected: "Chưa phát hiện",
        processingTitle: "Đang xử lý đối sánh tự động",
        processingDescription:
          "Kết quả theo quy tắc sẽ xuất hiện khi ảnh chụp CV và tin tuyển dụng sẵn sàng.",
        scoreComponents: "Các thành phần điểm số",
        automaticMatch: "Đối sánh tự động",
        aiAssessment: "Đánh giá AI",
        finalScore: "Điểm cuối",
        weightAutomatic: "Trọng số 40%",
        weightAi: "Trọng số 60%",
        result: "Kết quả",
        processing: "Đang xử lý",
        unavailable: "Chưa khả dụng",
        pending: "Đang chờ",
        formulaRetry: (score: number) =>
          `Đối sánh theo quy tắc ${score}/100 đã sẵn sàng · đang thử lại AI`,
        formulaUnavailable: (score: number) =>
          `Đối sánh theo quy tắc: ${score}/100 · AI chưa khả dụng`,
        incomplete: "Một phần dữ liệu nguồn có thể chưa đầy đủ.",
        requiredSkills: "Kỹ năng yêu cầu cho vai trò",
        foundInCv: "Tìm thấy trong CV",
        missingRequired: "Thiếu kỹ năng yêu cầu",
        preferredSkills: "Kỹ năng ưu tiên",
        experience: "Kinh nghiệm",
        minimumRequired: "Tối thiểu yêu cầu",
        years: (count: number) => `${count} năm`,
        notSpecified: "Chưa chỉ định",
        detectedInCv: "Phát hiện trong CV",
        notDetected: "Chưa phát hiện",
        noMinimum: "Không cấu hình yêu cầu tối thiểu",
        exceeds: (count: number) => `Vượt yêu cầu ${count} năm`,
        minimumNotEstablished: "Chưa xác định được kinh nghiệm tối thiểu",
        evidenceFound: "Bằng chứng tìm thấy trong CV",
        pages: "CV · trang 1–2",
        page: (count: number) => `Trang ${count}`,
        cv: "CV",
        noEvidence: "Không phát hiện đoạn bằng chứng cho ảnh chụp điểm này.",
      },
      assessment: {
        automaticMatch: "Đối sánh tự động",
        aiAssessment: "Đánh giá AI",
        finalScore: "Điểm cuối",
        processingTitle: "Đang xử lý đánh giá AI",
        processingDescription:
          "Kết quả theo quy tắc vẫn hiển thị trong khi tác vụ tính điểm ban đầu chạy nền.",
        processing: "Đang xử lý…",
        notCalculatedTitle: "Đánh giá AI chưa được tính",
        notCalculatedDescription:
          "Chưa có kết quả theo quy tắc được công bố để gửi cho AI đánh giá.",
        scoreCandidate: "Tính điểm ứng viên",
        rankingActions:
          "Có thể tính điểm AI từ các thao tác trên bảng xếp hạng ứng viên.",
        failedTitle: "Tính điểm CV thất bại",
        failedDescription: (code: string) =>
          `Tác vụ tính điểm đã kết thúc an toàn mà không công bố điểm${code ? ` (${code})` : ""}. Bạn có thể thử lại; đơn ứng tuyển vẫn khả dụng.`,
        retryScoring: "Tính điểm lại",
        retryingTitle: "Đang thử lại đánh giá AI",
        retryingDescription: (score: number | string) =>
          `Kết quả theo quy tắc ${score}/100 vẫn hiển thị trong khi AI chạy nền.`,
        retrying: "Đang thử lại…",
        ready: "Sẵn sàng",
        deterministicPreserved: "Đã bảo toàn kết quả theo quy tắc",
        retryInProgress: "Đang thử lại",
        willUpdate: "Sẽ cập nhật khi AI thành công",
        pending: "Đang chờ",
        willNotUseZero: "AI không được thay thế bằng điểm 0",
        notCalculated: "Chưa tính điểm",
        retryable: "Có thể thử lại",
        aiUnavailable: "AI chưa khả dụng",
        formulaRetry: (score: number | string) =>
          `Đối sánh theo quy tắc ${score} đã sẵn sàng · đang thử lại AI`,
        formulaUnavailable: (score: number) =>
          `Đối sánh theo quy tắc: ${score}/100 · AI chưa khả dụng`,
        repeatedFailure: (code: string) =>
          `AI thất bại nhiều lần (${code}) · hãy thử lại sau hoặc liên hệ hỗ trợ.`,
        methodNote:
          "Tab Đối sánh tự động vẫn khả dụng, bao gồm kỹ năng yêu cầu, kinh nghiệm và bằng chứng CV.",
        overall: "Đánh giá tổng thể",
        humanReview: "Cần con người xem xét.",
        lowQuality:
          "Chất lượng dữ liệu CV thấp nên đánh giá bị giới hạn. Hãy xem ghi chú phân tích trước khi dựa vào điểm số.",
        defaultHumanGuidance:
          "Hãy xem phần trích xuất và bằng chứng trước khi đưa ra quyết định tuyển dụng.",
        strengths: "Điểm mạnh dựa trên bằng chứng",
        pointsToVerify: "Điểm cần xác minh",
        aiPoints: "/ 100 điểm AI",
        scoreTier: "Nhóm điểm AI",
        whyScore: (score: number) => `Vì sao AI cho điểm ${score}?`,
        confidence: "Độ tin cậy",
        model: "Mô hình",
        prompt: "Prompt",
        reviewRequired: "Cần xem xét — hãy tự đánh giá cẩn thận bằng chứng.",
        suggestedQuestions: "Câu hỏi phỏng vấn gợi ý",
        noQuestions:
          "Không có đủ bằng chứng liên quan đến công việc để tạo câu hỏi riêng cho ứng viên.",
        scoreFormula: "Cách tính điểm này",
        automaticFormula: (score: number) => `Tự động ${score}`,
        noGaps: "Không xác định được khoảng trống đáng kể.",
        noStrengths: "Không thể tổng hợp điểm mạnh đáng tin cậy.",
      },
      documents: {
        pdfAttachment: "Tệp đính kèm PDF",
        writtenText: "Văn bản đã nhập",
        docxAttachment: "Tệp đính kèm DOCX",
        docAttachment: "Tệp đính kèm DOC",
        limitedPreview: "Bản xem trước giới hạn",
        parsedPreview: "Bản xem trước đã phân tích",
        loadingPreviews: "Đang tải bản xem trước…",
        cvPreviewFailed: "Bản xem trước CV thất bại",
        coverPreviewFailed: "Bản xem trước thư xin việc thất bại",
        previewFailed: "Bản xem trước thất bại",
        cvPdfReady: "Bản xem trước PDF CV gốc đã sẵn sàng",
        coverPdfReady: "Bản xem trước PDF thư xin việc gốc đã sẵn sàng",
        pdfReady: "Bản xem trước PDF gốc đã sẵn sàng",
        cvLimited: "Bản xem trước CV bị giới hạn",
        coverLimited: "Bản xem trước thư xin việc bị giới hạn",
        limited: "Bản xem trước tài liệu bị giới hạn",
        parserVersion: "Bản xem trước có cấu trúc v1",
        inProgress: "Đang xử lý…",
        parsedSuccessfully: "Phân tích thành công",
        processing: (seconds: string, snapshot: string, jd: string) =>
          `${seconds} giây · ảnh chụp CV ${snapshot} · JD ${jd}`,
        parseTimeout:
          "Phân tích mất nhiều hơn 7,5 giây. Hãy thử lại hoặc mở tệp gốc.",
        status: "Trạng thái bản xem trước tài liệu",
        processingTime: "Thời gian xử lý",
        originalStillAvailable:
          "Tệp gốc vẫn khả dụng. Hãy mở hoặc tải xuống để xem.",
        originalCv: "CV gốc",
        candidateCv: "CV ứng viên",
        coverLetter: "Thư xin việc",
        verification:
          "Dùng bản xem trước này để xác minh bằng chứng. Chọn “Xem CV gốc” hoặc “Xem thư xin việc” để mở toàn bộ tệp.",
        detectedKeywords: "Từ khóa phát hiện được",
        pdfPreview: (kind: string) => `${kind} PDF preview`,
        pages: (count: number) => `${count} trang`,
        pdfScroll: "PDF gốc · cuộn để xem các trang",
        coverAttached: "Đã đính kèm tệp thư xin việc",
        cvAttached: "Đã đính kèm CV gốc",
        textUnavailable:
          "Tệp khả dụng nhưng không thể trích xuất văn bản đọc được cho bản xem trước này.",
        completeUnavailable:
          "Không có bản xem trước văn bản đầy đủ. Hãy mở tệp gốc để kiểm tra phần còn lại.",
        viewOriginalFile: "Xem tệp gốc",
        pageIndicator: (count: number) => `1 / ${count}`,
        loadingOriginalPdf: "Đang tải PDF gốc…",
        candidateName: "CV ứng viên",
        professionalSummary: "Tóm tắt chuyên môn",
        experience: "Kinh nghiệm",
        skills: "Kỹ năng",
        education: "Học vấn",
        certifications: "Chứng chỉ",
        languages: "Ngôn ngữ",
        fieldsUnavailable: "Các trường CV có cấu trúc chưa khả dụng.",
        coverFieldsUnavailable:
          "Các trường thư xin việc có cấu trúc chưa khả dụng.",
        openOriginalToVerify: "Mở tệp gốc để kiểm tra phần nội dung còn lại.",
        coverNotProvided: "Chưa cung cấp thư xin việc",
        coverNotProvidedDescription: "Đơn này không có thư xin việc.",
        documentUnavailable: "Bản xem trước tài liệu chưa khả dụng",
        documentLoadFailed: "Không thể tải tài liệu",
        originalUnavailable: "Tài liệu gốc chưa khả dụng.",
        retryPreview: "Thử lại bản xem trước",
        loading: (title: string) => `Đang tải ${title}`,
        openOriginal: (title: string) => `Mở ${title} gốc`,
      },
      viewer: {
        originalDocument: "Tài liệu gốc",
        originalCv: "CV gốc",
        coverLetter: "Thư xin việc",
        close: "Đóng trình xem tài liệu",
        loading: "Đang tải bản xem trước tài liệu",
        loadFailed: "Không thể tải tài liệu",
        tryDownload: "Không thể tải tài liệu — hãy thử tải tệp gốc xuống.",
        empty: "Tài liệu trống.",
        downloadOnlyTitle: "Tệp gốc đã sẵn sàng",
        downloadOnlyDescription:
          "Định dạng này không thể hiển thị trực tiếp trong trình duyệt. Hãy tải xuống để xem toàn bộ CV hoặc thư xin việc.",
        downloadOriginal: "Tải tệp gốc xuống",
        downloadOriginalKind: (kind: string) => `Tải ${kind} gốc xuống`,
        preview: (kind: string) => `Bản xem trước ${kind}`,
      },
      rescore: {
        cancel: "Hủy",
        title: "Tính điểm lại ứng viên?",
        subtitle: (jobTitle: string) =>
          `${jobTitle} · Làm mới điểm toàn chiến dịch`,
        currentVisible:
          "Kết quả hiện tại vẫn hiển thị trong khi tính điểm lại. Mức ưu tiên thủ công được bảo toàn. Nếu AI chưa khả dụng, kết quả theo quy tắc vẫn hiển thị cho từng ứng viên.",
        start: "Bắt đầu tính điểm nền",
        starting: "Đang bắt đầu…",
        lead: (count: string) =>
          `Thao tác này sẽ tính điểm lại ${count} đơn ứng tuyển bằng phương pháp kết hợp 40/60 (40% đối sánh tự động và 60% đánh giá AI).`,
        jobDescription: "Mô tả công việc",
        scoringConfig: "Cấu hình tính điểm",
        executionMode: "Chế độ thực thi",
        backgroundJob: "Tác vụ nền",
        existingVisible:
          "Điểm hiện tại vẫn hiển thị đến khi kết quả thay thế sẵn sàng.",
        aiFailureSafe: "Lỗi AI không ghi đè bằng chứng theo quy tắc.",
        error: "Không thể bắt đầu tính điểm nền.",
      },
      priority: {
        cancel: "Hủy",
        title: "Đặt mức ưu tiên ứng viên thủ công",
        subtitle: (name: string) => `${name} · Ghi đè của nhà tuyển dụng`,
        info: "Bản thân điểm AI không thay đổi. Mục này được đánh dấu “Được ưu tiên thủ công” và được bảo toàn trong các lần tính điểm lại sau.",
        save: "Lưu mức ưu tiên",
        saving: "Đang lưu…",
        reference: "Thứ tự AI gợi ý · chỉ đọc",
        notCalculated: "Chưa tính điểm",
        finalScore: (score: number) => `Điểm cuối ${score}`,
        aiScore: "Điểm AI",
        select: "Chọn mức ưu tiên",
        manual: "Mức ưu tiên thủ công",
        reason: "Lý do ghi đè thủ công",
        required: "Bắt buộc",
        placeholder: "Giải thích cơ sở cho quyết định của nhà tuyển dụng.",
        remove: "Xóa mức ưu tiên thủ công",
        saveError: "Không thể lưu mức ưu tiên.",
        removeError: "Không thể xóa mức ưu tiên.",
        options: {
          HIGH: "Ưu tiên xem xét cao",
          NORMAL: "Ưu tiên xem xét trung bình",
          LOW: "Ưu tiên xem xét thấp",
          HOLD: "Giữ lại để xem sau",
        },
      },
      transition: {
        cancel: "Hủy",
        title: "Chuyển ứng viên sang phỏng vấn?",
        subtitle:
          "Quyết định rõ ràng của nhà tuyển dụng · Cập nhật vòng đơn ứng tuyển",
        info: "Đây là quyết định của bạn, không phải của AI. Thao tác được ghi vào lịch sử vòng và ứng viên sẽ nhận thông báo.",
        viewedInfo:
          " Vì ứng viên đang ở trạng thái Đã xem, thao tác sẽ ghi nhận Danh sách rút gọn trước khi chuyển sang Đang phỏng vấn.",
        confirm: "Xác nhận chuyển",
        moving: "Đang chuyển…",
        current: "Vòng hiện tại",
        recorded: "Vòng được ghi nhận",
        next: "Vòng tiếp theo",
        error: "Không thể hoàn tất chuyển sang phỏng vấn.",
      },
      reject: {
        cancel: "Hủy",
        title: "Từ chối ứng viên này?",
        subtitle: "Quyết định cuối cùng của con người",
        info: "AI không đưa ra quyết định này. Lý do, danh tính và thời điểm của bạn sẽ được lưu trong lịch sử vòng.",
        confirm: "Từ chối",
        rejecting: "Đang từ chối…",
        current: "Vòng hiện tại",
        next: "Vòng tiếp theo",
        rejected: "Đã từ chối",
        reason: "Lý do từ chối",
        required: "Bắt buộc",
        selectReason: "Chọn lý do chuẩn hóa",
        internalNote: "Ghi chú nội bộ",
        optional: "Không bắt buộc · chỉ dùng nội bộ · không gửi cho ứng viên",
        notePlaceholder: "Thêm bối cảnh cho nhóm tuyển dụng.",
        error: "Không thể từ chối ứng viên.",
        reasons: {
          REQUIRED_TECHNICAL_EXPERIENCE_NOT_DEMONSTRATED:
            "Chưa thể hiện kinh nghiệm kỹ thuật yêu cầu",
          INSUFFICIENT_EXPERIENCE: "Kinh nghiệm chưa đủ",
          REQUIRED_SKILLS_NOT_DEMONSTRATED: "Chưa thể hiện kỹ năng yêu cầu",
          POSITION_FILLED: "Vị trí đã đủ người",
          APPLICATION_WITHDRAWN_BY_CANDIDATE: "Ứng viên đã rút đơn",
          OTHER_JOB_RELATED_REASON: "Lý do khác liên quan đến công việc",
        },
      },
    };
  }

  return {
    stageLabels,
    drawer: {
      applyingFor: (jobTitle: string) => `Applying for ${jobTitle}`,
      close: "Close candidate details",
      closeDialog: "Close dialog",
      reviewInfo: "Review candidate information",
      recruitmentActions: "Candidate recruitment actions",
      viewCv: "View CV",
      viewCoverLetter: "View cover letter",
      viewProfile: "View profile",
      shortlist: "Shortlist",
      shortlisting: "Shortlisting…",
      openingChat: "Opening chat…",
      messageCandidate: "Message candidate",
      moveToInterview: "Move to interview",
      tabsLabel: "Candidate score details",
      automatic: "Automatic match",
      assessment: "AI assessment",
      documents: "CV & Cover letter",
      profile: "Profile",
      retry: "Retry",
      dismiss: "Dismiss",
      loadError: "Unable to load score explanation.",
      retryError: "AI retry could not be started.",
      scoreError: "Candidate scoring could not be started.",
      profileError: "Candidate profile is not available.",
      scoringFailed: "CV scoring failed",
      scoringStopped: (code: string) =>
        `The job stopped safely${code ? ` (${code})` : ""}. Retry scoring after correcting the CV or provider issue.`,
      retryScoring: "Retry scoring",
      aiUnavailable: "AI evaluation unavailable",
      retryAi: "Retry AI evaluation",
      aiRetrying: "Deterministic ready · AI retry in progress",
      aiRetryingDescription: (score: number | string) =>
        `The ${score}/100 result stays visible while AI runs in the background.`,
      scoringInProgress: "Scoring in progress",
      scoringInProgressDescription:
        "Partial results will appear here without blocking the rest of the candidate list.",
      rescoring: "Rescoring in progress · the current result stays visible.",
      profileReview: "Candidate profile review",
      currentProfile: "Current candidate profile",
      profileDescription:
        "Profile details reflect the candidate's active sharing choices.",
      noHeadline: "No headline shared",
      noSummary: "No summary shared",
      sharedSkills: "Shared skills",
      noSharedSections:
        "Current profile has no sections shared with recruiters.",
      contactShared:
        "Candidate has shared contact details for this application.",
      contactNotShared: "Contact details are not shared for this application.",
      humanDecision: "Human decision",
      scoreUnchanged: "Score unchanged",
      editPriority: "Edit priority",
      setPriority: "Set priority",
      reject: "Reject",
      assessmentView: "Assessment view",
      pending: "Pending",
      processing: "Processing",
      retryingAi: "Retrying AI",
      ruleBasedOnly: "Rule-based only",
      scoringFailedLabel: "Scoring failed",
      notCalculated: "Not calculated",
      hybridUnavailable: "Hybrid score unavailable",
      scoringJobFailed: "Scoring job failed",
      hybridPending: "Hybrid score pending",
      finalScore: "Final score",
      aiLabel: (label: string) => `AI: ${label}`,
      aiUnavailableMessage: (code: string) => {
        if (code === "AI_PROVIDER_INVALID_REQUEST")
          return "The AI provider rejected the assessment request. Check the provider/model configuration before retrying.";
        if (code === "AI_PROVIDER_MODEL_NOT_FOUND")
          return "The configured AI model is unavailable. Update the model configuration before retrying.";
        if (code === "AI_PROVIDER_AUTHENTICATION")
          return "The AI provider authentication failed. Check the server API key before retrying.";
        if (code === "AI_PROVIDER_POLICY_NOT_APPROVED")
          return "AI scoring is disabled by the current privacy or local-development configuration.";
        if (code === "AI_PROVIDER_NOT_CONFIGURED")
          return "The AI provider is not configured. Add the approved provider settings before retrying.";
        if (code === "AI_PROVIDER_MALFORMED")
          return "The AI provider returned an invalid assessment after automatic retries. Retry AI evaluation once; a worker restart is not required.";
        return "Deterministic matching is complete. The rule-based score and CV evidence remain visible while the AI provider is unavailable.";
      },
      retryDialogTitle: "Retry AI evaluation?",
      retryDialogSubtitle: (name: string) => `${name} · AI-only retry`,
      retryDialogInfo:
        "The deterministic result stays visible and is not recomputed. This retry is recorded as a recruiter action.",
      scoreDialogTitle: (label: string) => `${label}?`,
      scoreDialogSubtitle: (name: string) => `${name} · one application`,
      scoreDialogInfo:
        "Only this candidate will be queued. The score and assessment will update here when the background worker finishes.",
    },
    automatic: {
      lineagePreserved: "Lineage is preserved",
      scoreInputs: "Score inputs",
      config: "Config",
      noneDetected: "None detected",
      processingTitle: "Automatic match is processing",
      processingDescription:
        "The deterministic result will appear here when the CV and job snapshots are ready.",
      scoreComponents: "Score components",
      automaticMatch: "Automatic match",
      aiAssessment: "AI assessment",
      finalScore: "Final score",
      weightAutomatic: "Weight 40%",
      weightAi: "Weight 60%",
      result: "Result",
      processing: "Processing",
      unavailable: "Unavailable",
      pending: "Pending",
      formulaRetry: (score: number) =>
        `Deterministic ${score}/100 ready · AI retry in progress`,
      formulaUnavailable: (score: number) =>
        `Deterministic match: ${score}/100 · AI unavailable`,
      incomplete: "Some source data may be incomplete.",
      requiredSkills: "Skills required for the role",
      foundInCv: "Found in the CV",
      missingRequired: "Missing required skill",
      preferredSkills: "Preferred skills",
      experience: "Experience",
      minimumRequired: "Minimum required",
      years: (count: number) => `${count} year${count === 1 ? "" : "s"}`,
      notSpecified: "Not specified",
      detectedInCv: "Detected in the CV",
      notDetected: "Not detected",
      noMinimum: "No minimum configured",
      exceeds: (count: number) =>
        `Exceeds requirement by ${count} ${count === 1 ? "year" : "years"}`,
      minimumNotEstablished: "Minimum experience not established",
      evidenceFound: "Evidence found in the CV",
      pages: "CV · pages 1–2",
      page: (count: number) => `Page ${count}`,
      cv: "CV",
      noEvidence:
        "No evidence excerpts were detected for this scoring snapshot.",
    },
    assessment: {
      automaticMatch: "Automatic match",
      aiAssessment: "AI assessment",
      finalScore: "Final score",
      processingTitle: "AI assessment is processing",
      processingDescription:
        "The deterministic result will stay visible while the initial scoring operation runs in the background.",
      processing: "Processing…",
      notCalculatedTitle: "AI assessment is not calculated",
      notCalculatedDescription:
        "There is no published deterministic result to send for AI assessment yet.",
      scoreCandidate: "Score this candidate",
      rankingActions:
        "AI scoring is available from the candidate ranking actions.",
      failedTitle: "CV scoring failed",
      failedDescription: (code: string) =>
        `The scoring job ended safely without publishing a score${code ? ` (${code})` : ""}. You can retry it now; the candidate application is still available.`,
      retryScoring: "Retry scoring",
      retryingTitle: "Retrying AI evaluation",
      retryingDescription: (score: number | string) =>
        `The ${score}/100 deterministic result stays visible while AI runs in the background.`,
      retrying: "Retrying…",
      ready: "Ready",
      deterministicPreserved: "Deterministic result preserved",
      retryInProgress: "Retry in progress",
      willUpdate: "Will update when AI succeeds",
      pending: "Pending",
      willNotUseZero: "AI is not substituted with zero",
      notCalculated: "Not calculated",
      retryable: "Retryable state",
      aiUnavailable: "AI unavailable",
      formulaRetry: (score: number | string) =>
        `Deterministic ${score} ready · AI retry in progress`,
      formulaUnavailable: (score: number) =>
        `Deterministic match: ${score}/100 · AI unavailable`,
      repeatedFailure: (code: string) =>
        `Repeated AI failure (${code}) · try later or contact support.`,
      methodNote:
        "The Automatic match tab remains available, including required skills, experience, and CV evidence.",
      overall: "Overall assessment",
      humanReview: "Human review required.",
      lowQuality:
        "CV data quality is low, so this assessment is limited. Review the parsing notes before relying on this score.",
      defaultHumanGuidance:
        "Review the extraction and evidence before making a recruitment decision.",
      strengths: "Evidence-based strengths",
      pointsToVerify: "Points to verify",
      aiPoints: "/ 100 AI points",
      scoreTier: "AI score tier",
      whyScore: (score: number) => `Why did the AI give a score of ${score}?`,
      confidence: "Confidence",
      model: "Model",
      prompt: "Prompt",
      reviewRequired:
        "Review required — assess the evidence carefully yourself.",
      suggestedQuestions: "Suggested interview questions",
      noQuestions:
        "There is not enough job-relevant evidence to generate candidate-specific questions.",
      scoreFormula: "How this score is calculated",
      automaticFormula: (score: number) => `Automatic ${score}`,
      noGaps: "No significant gaps identified.",
      noStrengths: "No reliable strengths could be synthesized.",
    },
    documents: {
      pdfAttachment: "PDF attachment",
      writtenText: "Written text",
      docxAttachment: "DOCX attachment",
      docAttachment: "DOC attachment",
      limitedPreview: "Limited preview",
      parsedPreview: "Parsed preview",
      loadingPreviews: "Loading previews…",
      cvPreviewFailed: "CV preview failed",
      coverPreviewFailed: "Cover letter preview failed",
      previewFailed: "Preview failed",
      cvPdfReady: "Original CV PDF preview ready",
      coverPdfReady: "Original cover letter PDF preview ready",
      pdfReady: "Original PDF previews ready",
      cvLimited: "CV preview is limited",
      coverLimited: "Cover letter preview is limited",
      limited: "Document previews are limited",
      parserVersion: "Structured preview v1",
      inProgress: "In progress…",
      parsedSuccessfully: "Parsed successfully",
      processing: (seconds: string, snapshot: string, jd: string) =>
        `${seconds}s · CV snapshot ${snapshot} · JD ${jd}`,
      parseTimeout:
        "Parsing is taking longer than 7.5 seconds. Try again or open the original file.",
      status: "Document preview status",
      processingTime: "Processing time",
      originalStillAvailable:
        "Original files are still available. Open or download them to view.",
      originalCv: "Original CV",
      candidateCv: "Candidate CV",
      coverLetter: "Cover letter",
      verification:
        "Use this preview to verify evidence. Select “View original CV” or “View cover letter” to open the full file.",
      detectedKeywords: "Detected keywords",
      pdfPreview: (kind: string) => `${kind} PDF preview`,
      pages: (count: number) => `${count} page${count === 1 ? "" : "s"}`,
      pdfScroll: "Original PDF · scroll to view pages",
      coverAttached: "Cover letter file attached",
      cvAttached: "Original CV attached",
      textUnavailable:
        "The file is available, but readable text could not be extracted for this preview.",
      completeUnavailable:
        "A complete text preview was unavailable. Open the original file to verify the remaining content.",
      viewOriginalFile: "View original file",
      pageIndicator: (count: number) => `1 / ${count}`,
      loadingOriginalPdf: "Loading original PDF…",
      candidateName: "Candidate CV",
      professionalSummary: "Professional summary",
      experience: "Experience",
      skills: "Skills",
      education: "Education",
      certifications: "Certifications",
      languages: "Languages",
      fieldsUnavailable: "Structured CV fields are unavailable.",
      coverFieldsUnavailable: "Structured cover letter fields are unavailable.",
      openOriginalToVerify:
        "Open the original file to verify the remaining content.",
      coverNotProvided: "Cover letter not provided",
      coverNotProvidedDescription:
        "This application did not include a cover letter.",
      documentUnavailable: "Document preview unavailable",
      documentLoadFailed: "Couldn't load document",
      originalUnavailable: "The original document is not available.",
      retryPreview: "Retry preview",
      loading: (title: string) => `Loading ${title}`,
      openOriginal: (title: string) => `Open original ${title}`,
    },
    viewer: {
      originalDocument: "Original document",
      originalCv: "Original CV",
      coverLetter: "Cover letter",
      close: "Close document viewer",
      loading: "Loading document preview",
      loadFailed: "Couldn't load document",
      tryDownload: "Couldn't load document — try downloading the original.",
      empty: "The document is empty.",
      downloadOnlyTitle: "Original file is ready",
      downloadOnlyDescription:
        "This file format cannot be rendered inline in the browser. Download it to view the full CV or cover letter.",
      downloadOriginal: "Download original file",
      downloadOriginalKind: (kind: string) => `Download original ${kind}`,
      preview: (kind: string) => `${kind} preview`,
    },
    rescore: {
      cancel: "Cancel",
      title: "Rescore candidates?",
      subtitle: (jobTitle: string) =>
        `${jobTitle} · Campaign-wide scoring refresh`,
      currentVisible:
        "Current results stay visible during rescoring. Manual priorities are preserved. If AI is unavailable, the deterministic fallback remains visible for each candidate.",
      start: "Start background rescore",
      starting: "Starting…",
      lead: (count: string) =>
        `This will rescore ${count} applications using the 40/60 hybrid method (40% automatic matching and 60% AI evaluation).`,
      jobDescription: "Job description",
      scoringConfig: "Scoring config",
      executionMode: "Execution mode",
      backgroundJob: "Background job",
      existingVisible:
        "Existing scores stay visible until replacement results are ready.",
      aiFailureSafe: "AI failures do not overwrite deterministic evidence.",
      error: "The background rescore could not be started.",
    },
    priority: {
      cancel: "Cancel",
      title: "Set manual candidate priority",
      subtitle: (name: string) => `${name} · Recruiter override`,
      info: "The AI score itself never changes. This entry is marked “Manually prioritized” and is preserved during future rescoring.",
      save: "Save priority",
      saving: "Saving…",
      reference: "AI-suggested order · read-only reference",
      notCalculated: "Not calculated",
      finalScore: (score: number) => `Final score ${score}`,
      aiScore: "AI score",
      select: "Select a priority",
      manual: "Manual priority",
      reason: "Reason for manual override",
      required: "Required",
      placeholder: "Explain what informed this recruiter decision.",
      remove: "Remove manual priority",
      saveError: "Priority could not be saved.",
      removeError: "Priority could not be removed.",
      options: priorityLabels,
    },
    transition: {
      cancel: "Cancel",
      title: "Move candidate to interview?",
      subtitle: "Explicit recruiter decision · Application stage update",
      info: "This transition is made by you, not by AI. The action is recorded in stage history and the candidate is notified.",
      viewedInfo:
        " Because this candidate is Viewed, the action records Shortlisted before Interviewing.",
      confirm: "Confirm move",
      moving: "Moving…",
      current: "Current stage",
      recorded: "Recorded stage",
      next: "Next stage",
      error: "The interview transition could not be completed.",
    },
    reject: {
      cancel: "Cancel",
      title: "Reject this candidate?",
      subtitle: "Final human decision",
      info: "AI did not make this decision. Your reason, identity, and timestamp will be stored in stage history.",
      confirm: "Reject",
      rejecting: "Rejecting…",
      current: "Current stage",
      next: "Next stage",
      rejected: "Rejected",
      reason: "Rejection reason",
      required: "Required",
      selectReason: "Select a standardized reason",
      internalNote: "Internal note",
      optional: "Optional · internal use only · never sent to the candidate",
      notePlaceholder: "Add context for the recruiting team.",
      error: "The candidate could not be rejected.",
      reasons: rejectionReasons,
    },
  };
}

export type ApplicationDetailCopy = ReturnType<typeof applicationDetailCopy>;
