import type { WorkspaceLocale } from "@/frontend/features/dashboard/client/workspace-locale";

export function recruiterApplicationsCopy(locale: WorkspaceLocale) {
  return locale === "vi"
    ? {
        campaigns: {
          workspace: "Không gian nhà tuyển dụng",
          title: "Ứng viên",
          description:
            "Chọn một chiến dịch để xem đơn ứng tuyển, bằng chứng và điểm kết hợp trong một không gian tập trung.",
          campaign: (count: number) => `${count} chiến dịch`,
          active: "Đang tuyển",
          closed: "Đã đóng",
          updated: "Đã cập nhật",
          applicationReceived: "Đơn ứng tuyển đã nhận",
          updatedOn: (date: string) => `Đã cập nhật ${date}`,
          reviewCandidates: "Xem xét ứng viên",
          reviewCandidatesFor: (title: string) =>
            `Xem xét ứng viên cho ${title}`,
          viewPipeline: "Xem quy trình",
          viewPipelineFor: (title: string) => `Xem quy trình của ${title}`,
          insightsUpdating: "Đang cập nhật thông tin",
          insightsUnavailable: "Thông tin chưa khả dụng",
          insightsUpToDate: "Thông tin đã cập nhật",
          retry: "Thử lại",
          campaignDataUnavailable: "Dữ liệu chiến dịch chưa khả dụng",
          trustTitle: "Điểm số chỉ hỗ trợ ra quyết định.",
          trustDescription:
            "Điểm tự động và điểm AI giúp ưu tiên xem xét; quyết định tuyển dụng cuối cùng vẫn thuộc về nhà tuyển dụng.",
          searchCampaigns: "Tìm kiếm chiến dịch",
          searchPlaceholder: "Tìm theo vai trò, công ty hoặc phòng ban",
          status: "Trạng thái",
          allStatuses: "Tất cả trạng thái",
          department: "Phòng ban",
          allDepartments: "Tất cả phòng ban",
          campaignView: "Chế độ xem chiến dịch",
          gridView: "Chế độ xem lưới",
          listView: "Chế độ xem danh sách",
          showing: (start: number, end: number, total: number) =>
            `Hiển thị ${start}–${end} trên ${total} chiến dịch`,
          matchingFilters: "phù hợp với bộ lọc",
          readyForReview: "sẵn sàng để xem xét ứng viên",
          updatedJustNow: "Vừa cập nhật",
          refreshing: "Đang làm mới",
          refresh: "Làm mới",
          clearFilters: "Xóa bộ lọc",
          emptyReadyTitle: "Chưa có chiến dịch sẵn sàng để xem xét ứng viên",
          emptyReadyDescription:
            "Tin tuyển dụng đang hoạt động hoặc đã đóng sẽ xuất hiện ở đây sau khi sẵn sàng cho ứng viên.",
          emptyFilteredTitle: "Không có chiến dịch phù hợp với bộ lọc",
          emptyFilteredDescription:
            "Hãy thử vai trò, trạng thái hoặc phòng ban khác.",
          noTitle: "Tin tuyển dụng chưa có tiêu đề",
          candidates: (count: number) =>
            `${count.toLocaleString("vi-VN")} ứng viên`,
          pagination: {
            campaignsPerPage: "Số chiến dịch mỗi trang",
            previous: "Trang trước",
            next: "Trang sau",
            pagination: "Phân trang chiến dịch",
            page: (page: number) => `Trang ${page}`,
            perPage: (count: number) => `${count} / trang`,
          },
          distribution: {
            strong: "Phù hợp cao",
            review: "Cần xem xét",
            low: "Phù hợp thấp",
            summary: "Tóm tắt điểm ứng viên",
            unavailable: "Điểm số chưa khả dụng",
            inProgress: "Đang tính điểm",
            stillScoring: (count: number) =>
              `${count.toLocaleString("vi-VN")} ứng viên vẫn đang được tính điểm`,
            total: "tổng số",
          },
        },
        ranking: {
          breadcrumb: "Đường dẫn",
          recruitment: "Tuyển dụng",
          campaigns: "Chiến dịch",
          candidates: "Ứng viên",
          applications: "đơn ứng tuyển",
          lastScored: "Lần tính điểm gần nhất",
          notScored: "Chưa tính điểm",
          unavailable: "Chưa khả dụng",
          viewPipeline: "Xem quy trình",
          refreshing: "Đang làm mới…",
          refresh: "Làm mới",
          rescoring: "Đang tính lại…",
          rescoreCandidates: "Tính điểm lại ứng viên",
          dismissMessage: "Bỏ qua thông báo",
          rescoreProgress: "Đang tính lại",
          rescoreProgressDescription:
            "Kết quả sẽ tự động cập nhật. Điểm hiện tại vẫn hiển thị cho đến khi điểm thay thế sẵn sàng.",
          stats: {
            total: "Tổng số ứng viên",
            strong: "Phù hợp cao",
            review: "Cần xem xét",
            low: "Phù hợp thấp",
            processing: "Đang xử lý",
          },
          filters: {
            search: "Tìm kiếm",
            searchPlaceholder: "Tìm theo tên, email hoặc kỹ năng",
            totalScore: "Tổng điểm",
            anyScore: "Mọi mức điểm",
            requiredSkills: "Kỹ năng yêu cầu",
            anyRequiredSkill: "Mọi kỹ năng yêu cầu",
            experience: "Kinh nghiệm",
            anyExperience: "Mọi mức kinh nghiệm",
            years: (count: number) => `${count}+ năm`,
            recruitmentStatus: "Trạng thái tuyển dụng",
            scoringStatus: "Trạng thái tính điểm",
            allStatuses: "Tất cả trạng thái",
            activePipeline: "Quy trình đang hoạt động",
            new: "Mới",
            viewed: "Đã xem",
            shortlisted: "Vào danh sách rút gọn",
            needsDetails: "Cần bổ sung thông tin",
            interviewing: "Đang phỏng vấn",
            rejected: "Đã từ chối",
            withdrawn: "Đã rút hồ sơ",
            allScoringStates: "Tất cả trạng thái tính điểm",
            processing: "Đang xử lý",
            scored: "Đã tính điểm",
            aiUnavailable: "AI chưa khả dụng",
            scoringFailed: "Tính điểm thất bại",
            notCalculated: "Chưa tính",
            unknownStatus: "Trạng thái chưa xác định",
            resultCount: (count: number) =>
              `${count.toLocaleString("vi-VN")} ứng viên phù hợp với bộ lọc`,
            sortBy: "Sắp xếp theo",
            highestFinalScore: "Điểm cuối cao nhất",
            manualPriority: "Ưu tiên thủ công",
            mostRecentlyApplied: "Ứng tuyển gần đây nhất",
            clearFilters: "Xóa bộ lọc",
          },
          trustTitle: "Điểm số chỉ hỗ trợ ra quyết định.",
          trustDescription: "Nhà tuyển dụng đưa ra quyết định cuối cùng.",
          table: {
            rank: "Hạng",
            candidate: "Ứng viên",
            status: "Trạng thái",
            experience: "Kinh nghiệm",
            keySkills: "Kỹ năng chính",
            autoMatch: "Tự động",
            ai: "AI",
            finalScore: "Điểm cuối",
            applied: "Ngày ứng tuyển",
            manuallyPrioritized: "Được ưu tiên thủ công",
            extractingSkills: "Đang trích xuất kỹ năng",
            notDetected: "Chưa phát hiện",
            more: (count: number) => `+${count} kỹ năng khác`,
            year: "năm",
          },
          empty: {
            filteredTitle: "Không có ứng viên phù hợp với bộ lọc",
            filteredDescription:
              "Hãy điều chỉnh khoảng điểm hoặc một bộ lọc khác.",
            noCandidatesTitle: "Chưa có ứng viên ứng tuyển",
            noCandidatesDescription:
              "Ứng viên sẽ xuất hiện ở đây sau khi họ gửi đơn ứng tuyển.",
          },
          loading: "Đang tải bảng xếp hạng ứng viên",
          preparing: "Đang chuẩn bị bộ lọc và thứ tự điểm hiện tại…",
          loadError: "Không thể tải bảng xếp hạng ứng viên",
          retry: "Thử lại",
          paginationLabel: "Phân trang ứng viên",
          pagination: {
            showing: (start: number, end: number, total: number) =>
              `Hiển thị ${start}–${end} trên ${total} ứng viên`,
            perPage: "Số ứng viên mỗi trang",
            previous: "Trang trước",
            next: "Trang sau",
            page: (page: number) => `Trang ${page}`,
            candidates: "ứng viên",
          },
          actionMessages: {
            conversationNotReady:
              "Hãy mở chi tiết ứng viên cho đến khi đơn được đánh dấu là đã xem trước khi bắt đầu cuộc trò chuyện.",
            conversationUnavailable: "Không thể mở cuộc trò chuyện tuyển dụng.",
            shortlistFailed: "Không thể đưa ứng viên vào danh sách rút gọn.",
            rescoreStarted:
              "Đã bắt đầu tính điểm lại ở chế độ nền. Điểm hiện tại vẫn hiển thị trong khi kết quả được cập nhật.",
            prioritySaved:
              "Đã lưu ưu tiên thủ công và sẽ giữ nguyên trong lần tính điểm lại.",
            movedToInterview:
              "Đã chuyển ứng viên sang vòng phỏng vấn. Lịch sử vòng tuyển dụng và thông báo đã được ghi nhận.",
            candidateRejected:
              "Đã từ chối ứng viên. Lý do đã được lưu trong lịch sử vòng tuyển dụng.",
          },
        },
        pipeline: {
          workspace: "Không gian nhà tuyển dụng",
          title: "Quy trình ứng viên",
          pipelineFor: (title: string) => `Quy trình ứng viên của ${title}`,
          subtitle:
            "Xem tiến độ ứng viên qua từng vòng trong quy trình tuyển dụng của bạn.",
          jobPosting: "Tin tuyển dụng",
          untitledJob: "Tin tuyển dụng chưa có tiêu đề",
          active: "Đang tuyển",
          closed: "Đã đóng",
          selectDescription:
            "Chọn một tin tuyển dụng đang quản lý để xem quy trình ứng viên.",
          chooseJob: "Chọn một tin tuyển dụng",
          showingPipeline: (title: string) =>
            `Đang hiển thị quy trình của ${title}.`,
          selectJob: "Chọn một tin tuyển dụng để tải quy trình.",
          noJobsTitle: "Chưa có tin tuyển dụng",
          noJobsDescription:
            "Hãy tạo hoặc xuất bản tin tuyển dụng trước khi mở quy trình đánh giá ứng viên.",
          createJob: "Tạo tin tuyển dụng",
          selectJobTitle: "Chọn tin tuyển dụng",
          selectJobDescription:
            "Chọn một tin ở trên để xem ứng viên được nhóm theo từng vòng.",
          activePipeline: "Quy trình đang hoạt động",
          activePipelineDescription:
            "Các đơn đang đi qua quy trình tuyển dụng.",
          outcomes: "Kết quả",
          outcomesDescription: "Các đơn đã đóng hoặc đang tạm dừng.",
          loading: "Đang tải quy trình tuyển dụng…",
          unavailable: "Quy trình tuyển dụng hiện chưa khả dụng.",
          unexpectedStage:
            "Danh sách ứng viên trả về không đúng vòng tuyển dụng.",
          stageChangeFailed: "Không thể lưu thay đổi vòng tuyển dụng.",
          movingToStage: (name: string, stage: string) =>
            `Đang chuyển ${name} sang ${stage}.`,
          movedSuccessfully: (name: string) => `Đã chuyển ${name} thành công.`,
          unknownStage: "Vòng chưa xác định",
          retry: "Thử lại",
          readOnly: "Quyền chỉ đọc",
          refresh: "Làm mới",
          retryStageChange: "Thử lại thay đổi vòng",
          searchCandidates: "Tìm ứng viên theo tên",
          searchPlaceholder: "Tìm theo tên ứng viên…",
          tierFilter: "Lọc ứng viên theo nhóm điểm cuối",
          sort: "Sắp xếp",
          lowHigh: "Thấp → cao",
          highLow: "Cao → thấp",
          defaultSort: "Mặc định",
          scoreLowHigh: "Điểm: thấp → cao",
          scoreHighLow: "Điểm: cao → thấp",
          stageLocked: "Vòng tuyển dụng đã khóa",
          withdrawnLocked: "Đơn đã rút không thể di chuyển",
          sortCandidates: (label: string) => `Sắp xếp ứng viên ${label}`,
          sortOptions: (label: string) => `Tùy chọn sắp xếp ${label}`,
          loadingApplications: "Đang tải đơn ứng tuyển…",
          noFilterMatch:
            "Không có ứng viên đã tải phù hợp với bộ lọc hiện tại.",
          noCandidates: "Chưa có ứng viên.",
          loadMore: (label: string) => `Tải thêm đơn ${label}`,
          viewFullList: "Xem toàn bộ danh sách",
          dragToStage: (name: string) => `Kéo ${name} sang vòng khác`,
          dragCard: "Kéo thẻ",
          openCv: "Mở CV",
          coverLetter: "Thư xin việc",
          viewAiAssessment: "Xem đánh giá AI",
          changeStage: "Thay đổi vòng…",
          clickActions: "Nhấp để xem thao tác",
          clickCollapse: "Nhấp để thu gọn",
          submitted: (date: string) => `Đã nộp ${date}`,
          finalScore: "Điểm cuối",
          finalScoreUnavailable: "Chưa có điểm cuối",
          candidatePreview: "Xem nhanh ứng viên",
          previewHint: "Rê chuột hoặc chọn một ứng viên để xem nhanh.",
          pinPreview: "Giữ bảng xem nhanh",
          closePreview: "Đóng bảng xem nhanh",
          stage: "Vòng tuyển dụng",
          submittedLabel: "Ngày nộp",
          documents: "Tài liệu",
          cvAvailable: "Có CV",
          cvUnavailable: "Chưa có CV",
          finalScoreFor: (score: number, name: string) =>
            `Điểm cuối ${score}% cho ${name}`,
          moveToShortlist: "Chuyển vào danh sách rút gọn",
          moveToInterview: "Chuyển sang phỏng vấn",
          sendOffer: "Gửi đề nghị",
          reject: "Từ chối",
          waitlist: "Đưa vào danh sách chờ",
          stageLabels: {
            APPLIED: "Mới",
            VIEWED: "Đã xem",
            SHORTLISTED: "Vào danh sách rút gọn",
            INTERVIEWING: "Đang phỏng vấn",
            OFFERED: "Đã đề nghị",
            HIRED: "Đã tuyển",
            OFFER_DECLINED: "Từ chối đề nghị",
            REJECTED: "Đã từ chối",
            WAITLISTED: "Danh sách chờ",
            WITHDRAWN: "Đã rút hồ sơ",
          },
          showingAll: "Đang hiển thị tất cả ứng viên đã tải.",
          showingFiltered: (tier: string, query: string) =>
            `Đang hiển thị ứng viên đã tải, lọc theo ${tier}${query ? ` và ${query}` : ""}.`,
          all: "Tất cả",
          strong: "Phù hợp cao",
          review: "Cần xem xét",
          low: "Phù hợp thấp",
          pending: "Chưa tính điểm",
          drag: {
            picked: (id: string) => `Đã chọn đơn ứng tuyển ${id}.`,
            over: (id: string) => `Đang ở trên ${id}.`,
            notOver: "Chưa ở trên một vòng nào.",
            dropped: (id: string) => `Đã thả vào ${id}.`,
            cancelled: "Đã hủy di chuyển.",
          },
          bulkRejectTitle: (count: number) => `Từ chối ${count} ứng viên?`,
          candidates: "ứng viên",
          bulkRejectDescription:
            "Chọn một lý do từ chối bắt buộc cho tất cả ứng viên đã chọn.",
          fullList: "DANH SÁCH ĐẦY ĐỦ ỨNG VIÊN",
          totalInStage: (count: number) =>
            `Tổng cộng ${count} ứng viên trong vòng này.`,
          closeFullList: "Đóng danh sách đầy đủ",
          selectAll: "Chọn tất cả trong danh sách này",
          selected: (count: number) => `Đã chọn ${count} ứng viên`,
          noneSelected: "Chưa chọn ứng viên nào",
          loadingFullList: "Đang tải danh sách đầy đủ ứng viên…",
          noCandidatesInStage: "Chưa có ứng viên trong vòng này.",
          selectCandidate: (name: string) => `Chọn ${name}`,
          confirmBulk: (action: string, count: number, stage: string) =>
            `${action} ${count} ứng viên đã chọn khỏi ${stage}?`,
        },
        submitted: {
          back: "Quay lại tin tuyển dụng",
          eyebrow: "Ứng viên đã nộp",
          description:
            "Xem bằng chứng ứng viên đã nộp cho tin tuyển dụng này. Điểm số không nằm trong màn hình này.",
          refresh: "Làm mới",
          refreshing: "Đang làm mới…",
          loading: "Đang tải ứng viên đã nộp…",
          updating: "Đang cập nhật ứng viên đã nộp…",
          loadError: "Không thể tải ứng viên đã nộp.",
          retry: "Thử lại",
          empty: "Chưa có ứng viên nộp đơn cho tin tuyển dụng này.",
          list: "Ứng viên đã nộp",
          viewCv: "Xem CV",
          downloadCv: "Tải CV",
          viewCoverLetter: "Xem thư xin việc",
          downloadCoverLetter: "Tải thư xin việc",
          coverLetterMissing: "Chưa cung cấp",
          applied: (date: string) => `Đã ứng tuyển ${date}`,
          loadMore: "Tải thêm ứng viên",
          loadingMore: "Đang tải…",
        },
        stageDialog: {
          titleFor: (name: string) => `Thay đổi vòng cho ${name}`,
          description: "Chọn một đích đến được trả về cho đơn ứng tuyển này.",
          destination: "Vòng đích",
          chooseStage: "Chọn một vòng",
          rejectionReason: "Lý do từ chối",
          chooseReason: "Chọn một lý do",
          privateNote: "Ghi chú riêng cho nhà tuyển dụng (không bắt buộc)",
          neverShared: "Không bao giờ chia sẻ với ứng viên.",
          offerDeclinedReason: "Lý do từ chối đề nghị",
          cancel: "Hủy",
          saving: "Đang lưu…",
          confirmRejection: "Xác nhận từ chối",
          confirmHiring: "Xác nhận tuyển dụng",
          confirmOfferDeclined: "Xác nhận từ chối đề nghị",
          confirmStageChange: "Xác nhận thay đổi vòng",
          changeStage: "Thay đổi vòng",
          rejectionReasons: {
            REQUIRED_TECHNICAL_EXPERIENCE_NOT_DEMONSTRATED:
              "Chưa thể hiện kinh nghiệm kỹ thuật yêu cầu",
            INSUFFICIENT_EXPERIENCE: "Kinh nghiệm chưa đủ",
            REQUIRED_SKILLS_NOT_DEMONSTRATED: "Chưa thể hiện kỹ năng yêu cầu",
            POSITION_FILLED: "Vị trí đã có người đảm nhiệm",
            APPLICATION_WITHDRAWN_BY_CANDIDATE: "Ứng viên đã rút đơn",
            OTHER_JOB_RELATED_REASON: "Lý do khác liên quan đến việc làm",
          },
        },
      }
    : {
        campaigns: {
          workspace: "Recruiter workspace",
          title: "Candidates",
          description:
            "Choose a campaign to review applications, evidence, and hybrid scoring in one focused workspace.",
          campaign: (count: number) => `${count} campaigns`,
          active: "Active",
          closed: "Closed",
          updated: "Updated",
          applicationReceived: "Applications received",
          updatedOn: (date: string) => `Updated ${date}`,
          reviewCandidates: "Review candidates",
          reviewCandidatesFor: (title: string) =>
            `Review candidates for ${title}`,
          viewPipeline: "View pipeline",
          viewPipelineFor: (title: string) => `View pipeline for ${title}`,
          insightsUpdating: "Updating insights",
          insightsUnavailable: "Insights unavailable",
          insightsUpToDate: "Insights up to date",
          retry: "Retry",
          campaignDataUnavailable: "Campaign data unavailable",
          trustTitle: "Scores support decision-making only.",
          trustDescription:
            "Automatic and AI scores help you prioritize review; every hiring decision remains with the recruiter.",
          searchCampaigns: "Search campaigns",
          searchPlaceholder: "Search by role, company, or department",
          status: "Status",
          allStatuses: "All statuses",
          department: "Department",
          allDepartments: "All departments",
          campaignView: "Campaign view",
          gridView: "Grid view",
          listView: "List view",
          showing: (start: number, end: number, total: number) =>
            `Showing ${start}–${end} of ${total} campaigns`,
          matchingFilters: "matching your filters",
          readyForReview: "ready for candidate review",
          updatedJustNow: "Updated just now",
          refreshing: "Refreshing",
          refresh: "Refresh",
          clearFilters: "Clear filters",
          emptyReadyTitle: "No campaigns are ready for candidate review",
          emptyReadyDescription:
            "Active and closed job postings will appear here after they are available to candidates.",
          emptyFilteredTitle: "No campaigns match these filters",
          emptyFilteredDescription:
            "Try a different role, status, or department.",
          noTitle: "Untitled job posting",
          candidates: (count: number) =>
            `${count.toLocaleString("en-US")} candidates`,
          pagination: {
            campaignsPerPage: "Campaigns per page",
            previous: "Previous page",
            next: "Next page",
            pagination: "Campaign pagination",
            page: (page: number) => `Page ${page}`,
            perPage: (count: number) => `${count} / page`,
          },
          distribution: {
            strong: "Strong match",
            review: "Review needed",
            low: "Low match",
            summary: "Candidate scoring summary",
            unavailable: "Scoring unavailable",
            inProgress: "Scoring in progress",
            stillScoring: (count: number) =>
              `${count.toLocaleString("en-US")} candidates still scoring`,
            total: "total",
          },
        },
        ranking: {
          breadcrumb: "Breadcrumb",
          recruitment: "Recruitment",
          campaigns: "Campaigns",
          candidates: "Candidates",
          applications: "applications",
          lastScored: "Last scored",
          notScored: "Not yet scored",
          unavailable: "Unavailable",
          viewPipeline: "View pipeline",
          refreshing: "Refreshing…",
          refresh: "Refresh",
          rescoring: "Rescoring…",
          rescoreCandidates: "Rescore candidates",
          dismissMessage: "Dismiss message",
          rescoreProgress: "Rescoring in progress",
          rescoreProgressDescription:
            "Results will update automatically. Current scores stay visible until replacements are ready.",
          stats: {
            total: "Total candidates",
            strong: "Strong match",
            review: "Review needed",
            low: "Low match",
            processing: "Processing",
          },
          filters: {
            search: "Search",
            searchPlaceholder: "Search by name, email, or skill",
            totalScore: "Total score",
            anyScore: "Any score",
            requiredSkills: "Required skills",
            anyRequiredSkill: "Any required skill",
            experience: "Experience",
            anyExperience: "Any experience",
            years: (count: number) => `${count}+ years`,
            recruitmentStatus: "Recruitment status",
            scoringStatus: "Scoring status",
            allStatuses: "All statuses",
            activePipeline: "Active pipeline",
            new: "New",
            viewed: "Viewed",
            shortlisted: "Shortlisted",
            needsDetails: "Needs details",
            interviewing: "Interviewing",
            rejected: "Rejected",
            withdrawn: "Withdrawn",
            allScoringStates: "All scoring states",
            processing: "Processing",
            scored: "Scored",
            aiUnavailable: "AI unavailable",
            scoringFailed: "Scoring failed",
            notCalculated: "Not calculated",
            unknownStatus: "Unknown status",
            resultCount: (count: number) =>
              `${count.toLocaleString("en-US")} candidates match the filters`,
            sortBy: "Sort by",
            highestFinalScore: "Highest final score",
            manualPriority: "Manual priority",
            mostRecentlyApplied: "Most recently applied",
            clearFilters: "Clear filters",
          },
          trustTitle: "Scores support decision-making only.",
          trustDescription: "The recruiter makes the final decision.",
          table: {
            rank: "Rank",
            candidate: "Candidate",
            status: "Status",
            experience: "Experience",
            keySkills: "Key skills",
            autoMatch: "Auto match",
            ai: "AI",
            finalScore: "Final score",
            applied: "Applied",
            manuallyPrioritized: "Manually prioritized",
            extractingSkills: "Extracting skills",
            notDetected: "Not detected",
            more: (count: number) => `+${count} more`,
            year: "year",
          },
          empty: {
            filteredTitle: "No candidates match these filters",
            filteredDescription:
              "Try adjusting your score range or another filter.",
            noCandidatesTitle: "No candidates have applied yet",
            noCandidatesDescription:
              "Candidates will appear here after they submit an application.",
          },
          loading: "Loading candidate ranking",
          preparing: "Preparing the current filters and score order…",
          loadError: "Candidate ranking could not be loaded",
          retry: "Retry",
          paginationLabel: "Candidate pagination",
          pagination: {
            showing: (start: number, end: number, total: number) =>
              `Showing ${start}–${end} of ${total} candidates`,
            perPage: "Candidates per page",
            previous: "Previous page",
            next: "Next page",
            page: (page: number) => `Page ${page}`,
            candidates: "candidates",
          },
          actionMessages: {
            conversationNotReady:
              "Open the candidate details until the application is marked viewed before starting a conversation.",
            conversationUnavailable:
              "The recruitment conversation could not be opened.",
            shortlistFailed: "The candidate could not be shortlisted.",
            rescoreStarted:
              "Background rescore started. Existing scores remain visible while results update.",
            prioritySaved:
              "Manual priority saved and will be preserved during rescoring.",
            movedToInterview:
              "Candidate moved to Interviewing. The stage history and notification were recorded.",
            candidateRejected:
              "Candidate rejected. The reason was stored in stage history.",
          },
        },
        pipeline: {
          workspace: "Recruiter workspace",
          title: "Candidate pipeline",
          pipelineFor: (title: string) => `${title} pipeline`,
          subtitle:
            "Review candidate progress across each stage of your hiring workflow.",
          jobPosting: "Job posting",
          untitledJob: "Untitled job posting",
          active: "Active",
          closed: "Closed",
          selectDescription:
            "Select one managed job to view its candidate pipeline.",
          chooseJob: "Choose a job posting",
          showingPipeline: (title: string) =>
            `Showing the pipeline for ${title}.`,
          selectJob: "Select a job to load its pipeline.",
          noJobsTitle: "No job postings available",
          noJobsDescription:
            "Create or publish a job posting before opening its candidate evaluation pipeline.",
          createJob: "Create a job posting",
          selectJobTitle: "Select a job posting",
          selectJobDescription:
            "Choose a job above to see its candidates grouped by stage.",
          activePipeline: "Active pipeline",
          activePipelineDescription:
            "Applications moving through the hiring process.",
          outcomes: "Outcomes",
          outcomesDescription: "Closed or paused applications.",
          loading: "Loading recruitment pipeline…",
          unavailable: "The recruitment pipeline is unavailable.",
          unexpectedStage: "The candidate list returned an unexpected stage.",
          stageChangeFailed: "The stage change was not saved.",
          movingToStage: (name: string, stage: string) =>
            `Moving ${name} to ${stage}.`,
          movedSuccessfully: (name: string) => `${name} moved successfully.`,
          unknownStage: "Unknown stage",
          retry: "Retry",
          readOnly: "Read-only access",
          refresh: "Refresh",
          retryStageChange: "Retry stage change",
          searchCandidates: "Search candidates by name",
          searchPlaceholder: "Search by candidate name...",
          tierFilter: "Filter candidates by final-score tier",
          sort: "Sort",
          lowHigh: "Low → High",
          highLow: "High → Low",
          defaultSort: "Default",
          scoreLowHigh: "Score: Low → High",
          scoreHighLow: "Score: High → Low",
          stageLocked: "Stage is locked",
          withdrawnLocked: "Withdrawn applications cannot be moved",
          sortCandidates: (label: string) => `Sort ${label} candidates`,
          sortOptions: (label: string) => `${label} sort options`,
          loadingApplications: "Loading applications…",
          noFilterMatch: "No loaded candidates match the current filter.",
          noCandidates: "No candidates yet.",
          loadMore: (label: string) => `Load more ${label} applications`,
          viewFullList: "View full list",
          dragToStage: (name: string) => `Drag ${name} to another stage`,
          dragCard: "Drag card",
          openCv: "Open CV",
          coverLetter: "Cover letter",
          viewAiAssessment: "View AI assessment",
          changeStage: "Change stage…",
          clickActions: "Click to view actions",
          clickCollapse: "Click to collapse",
          submitted: (date: string) => `Submitted ${date}`,
          finalScore: "Final score",
          finalScoreUnavailable: "Final score not yet available",
          candidatePreview: "Candidate preview",
          previewHint: "Hover over or select a candidate to preview their details.",
          pinPreview: "Keep preview open",
          closePreview: "Close preview",
          stage: "Pipeline stage",
          submittedLabel: "Submitted",
          documents: "Documents",
          cvAvailable: "CV available",
          cvUnavailable: "No CV available",
          finalScoreFor: (score: number, name: string) =>
            `Final score ${score} percent for ${name}`,
          moveToShortlist: "Move to shortlist",
          moveToInterview: "Move to interview",
          sendOffer: "Send offer",
          reject: "Reject",
          waitlist: "Waitlist",
          stageLabels: {
            APPLIED: "New",
            VIEWED: "Viewed",
            SHORTLISTED: "Shortlisted",
            INTERVIEWING: "Interviewing",
            OFFERED: "Offer",
            HIRED: "Hired",
            OFFER_DECLINED: "Offer declined",
            REJECTED: "Rejected",
            WAITLISTED: "Needs details",
            WITHDRAWN: "Withdrawn",
          },
          showingAll: "Showing all loaded candidates.",
          showingFiltered: (tier: string, query: string) =>
            `Showing loaded candidates filtered by ${tier}${query ? ` and ${query}` : ""}.`,
          all: "All",
          strong: "Strong match",
          review: "Review needed",
          low: "Low match",
          pending: "Not yet scored",
          drag: {
            picked: (id: string) => `Picked up application ${id}.`,
            over: (id: string) => `Over ${id}.`,
            notOver: "Not over a stage.",
            dropped: (id: string) => `Dropped in ${id}.`,
            cancelled: "Move cancelled.",
          },
          bulkRejectTitle: (count: number) => `Reject ${count} candidates?`,
          candidates: "candidates",
          bulkRejectDescription:
            "Choose one required rejection reason for every selected candidate.",
          fullList: "FULL CANDIDATE LIST",
          totalInStage: (count: number) =>
            `Total ${count} candidates in this stage.`,
          closeFullList: "Close full list",
          selectAll: "Select all in this list",
          selected: (count: number) => `${count} candidates selected`,
          noneSelected: "No candidates selected",
          loadingFullList: "Loading full candidate list…",
          noCandidatesInStage: "No candidates in this stage.",
          selectCandidate: (name: string) => `Select ${name}`,
          confirmBulk: (action: string, count: number, stage: string) =>
            `${action} ${count} selected candidates from ${stage}?`,
        },
        submitted: {
          back: "Back to job postings",
          eyebrow: "Submitted candidates",
          description:
            "Review the evidence candidates submitted for this job. Scores are not part of this view.",
          refresh: "Refresh",
          refreshing: "Refreshing…",
          loading: "Loading submitted candidates…",
          updating: "Updating submitted candidates…",
          loadError: "Submitted candidates could not be loaded.",
          retry: "Retry",
          empty: "No candidates have applied to this job yet.",
          list: "Submitted candidates",
          viewCv: "View CV",
          downloadCv: "Download CV",
          viewCoverLetter: "View cover letter",
          downloadCoverLetter: "Download cover letter",
          coverLetterMissing: "Not provided",
          applied: (date: string) => `Applied ${date}`,
          loadMore: "Load more candidates",
          loadingMore: "Loading…",
        },
        stageDialog: {
          titleFor: (name: string) => `Change stage for ${name}`,
          description: "Choose one destination returned for this application.",
          destination: "Destination stage",
          chooseStage: "Choose a stage",
          rejectionReason: "Rejection reason",
          chooseReason: "Choose a reason",
          privateNote: "Private recruiter note (optional)",
          neverShared: "Never shared with the candidate.",
          offerDeclinedReason: "Offer declined reason",
          cancel: "Cancel",
          saving: "Saving…",
          confirmRejection: "Confirm rejection",
          confirmHiring: "Confirm hiring",
          confirmOfferDeclined: "Confirm offer declined",
          confirmStageChange: "Confirm stage change",
          changeStage: "Change stage",
          rejectionReasons: {
            REQUIRED_TECHNICAL_EXPERIENCE_NOT_DEMONSTRATED:
              "Required technical experience not demonstrated",
            INSUFFICIENT_EXPERIENCE: "Insufficient experience",
            REQUIRED_SKILLS_NOT_DEMONSTRATED:
              "Required skills not demonstrated",
            POSITION_FILLED: "Position filled",
            APPLICATION_WITHDRAWN_BY_CANDIDATE:
              "Application withdrawn by candidate",
            OTHER_JOB_RELATED_REASON: "Other job-related reason",
          },
        },
      };
}

export type RecruiterApplicationsCopy = ReturnType<
  typeof recruiterApplicationsCopy
>;
