import { z } from "zod";

export const authenticationAuditAction = z.enum([
  "registration.accepted",
  "registration.rejected",
  "verification.succeeded",
  "verification.failed",
  "verification.resent",
  "verification.resend_ignored",
  "rate_limit.denied",
  "email.delivery_failed",
  "password.policy_rejected",
  "password.compromised_rejected",
  "login.succeeded",
  "login.failed",
  "logout.succeeded",
  "session.revoked",
  "session.revoked_all",
  "totp.enrollment_started",
  "totp.enabled",
  "totp.disabled",
  "totp.challenge_succeeded",
  "totp.challenge_failed",
  "backup_codes.regenerated",
  "backup_code.consumed",
  "password_reset.requested",
  "password_reset.intent_recorded",
  "password_reset.succeeded",
  "password_reset.failed",
  "account_recovery.requested",
  "account_recovery.confirmation_intent_recorded",
  "account_recovery.hold_started",
  "account_recovery.completion_intent_recorded",
  "account_recovery.cancelled",
  "account_recovery.completed",
  "account_recovery.failed",
  "account.activated",
  "account.suspended",
  "account.deleted",
  "email_change.requested",
  "email_change.rejected",
  "email_change.superseded",
  "email_change.verified",
  "email_change.verification_failed",
  "password_change.intent_recorded",
  "password_change.succeeded",
  "password_change.failed",
  "password_change.locked",
  "job.report.submitted",
  "job.report.denied",
  "job.application.submitted",
  "job.application.denied",
  "job.application.failed",
]);

const auditContextSchema = z
  .object({
    reason: z.string().max(160).optional(),
    stage: z.string().max(160).optional(),
    state: z.string().max(160).optional(),
    status: z.string().max(160).optional(),
    kind: z.string().max(160).optional(),
    failureCode: z.string().max(160).optional(),
    count: z.number().finite().optional(),
    attemptCount: z.number().finite().optional(),
    holdHours: z.number().finite().optional(),
    eligible: z.boolean().optional(),
    passwordOwner: z.string().max(160).optional(),
    sessionRevocation: z.string().max(160).optional(),
    twoFactorPreserved: z.boolean().optional(),
    sessionsRevoked: z.boolean().optional(),
    otherSessionsRevoked: z.boolean().optional(),
    challengesInvalidated: z.boolean().optional(),
    previousSessionsRemainRevoked: z.boolean().optional(),
    twoFactorDisabled: z.boolean().optional(),
    backupCodesInvalidated: z.boolean().optional(),
    automaticSessionCreated: z.boolean().optional(),
    duplicate: z.boolean().optional(),
    notificationWorkCount: z.number().int().nonnegative().optional(),
  })
  .strict();

export const authenticationAuditEventSchema = z
  .object({
    occurredAt: z.date(),
    actorType: z.enum(["anonymous", "user", "system"]),
    actorUserId: z.string().min(1).nullable().optional(),
    actorSessionId: z.string().min(1).nullable().optional(),
    action: authenticationAuditAction,
    targetType: z.enum([
      "user_account",
      "email_verification",
      "request",
      "email_outbox",
      "session",
      "two_factor",
      "password_reset",
      "account_recovery",
      "email_change",
      "password_change",
      "job_posting",
      "job_report",
      "job_application",
    ]),
    targetId: z.string().min(1).nullable().optional(),
    result: z.enum(["SUCCESS", "FAILURE", "DENIED"]),
    correlationId: z.string().min(8).max(128),
    ipPrefixDigest: z.string().max(128).nullable().optional(),
    userAgentFamily: z.string().max(80).nullable().optional(),
    context: auditContextSchema,
  })
  .strict();

export type AuthenticationAuditEvent = z.infer<
  typeof authenticationAuditEventSchema
>;
