import { z } from "zod";

export const authenticationAuditAction = z.enum([
  "registration.accepted",
  "registration.rejected",
  "verification.succeeded",
  "verification.failed",
  "verification.resent",
  "verification.resend_ignored",
  "rate_limit.denied",
  "email.delivery_failed",
  "password.policy_rejected",
  "password.compromised_rejected",
  "login.succeeded",
  "login.failed",
  "logout.succeeded",
  "session.revoked",
  "session.revoked_all",
  "totp.enrollment_started",
  "totp.enabled",
  "totp.disabled",
  "totp.challenge_succeeded",
  "totp.challenge_failed",
  "backup_codes.regenerated",
  "backup_code.consumed",
  "password_reset.requested",
  "password_reset.intent_recorded",
  "password_reset.succeeded",
  "password_reset.failed",
  "account_recovery.requested",
  "account_recovery.confirmation_intent_recorded",
  "account_recovery.hold_started",
  "account_recovery.completion_intent_recorded",
  "account_recovery.cancelled",
  "account_recovery.completed",
  "account_recovery.failed",
  "account.activated",
  "account.suspended",
  "account.deleted",
  "email_change.requested",
  "email_change.rejected",
  "email_change.superseded",
  "email_change.verified",
  "email_change.verification_failed",
  "password_change.intent_recorded",
  "password_change.succeeded",
  "password_change.failed",
  "password_change.locked",
  "job.report.submitted",
  "job.report.denied",
  "job.application.submitted",
  "job.application.stage_changed",
  "job.application.withdrawn",
  "job.application.denied",
  "job.application.failed",
  "job_posting.capacity_changed",
  "job_posting.created",
  "job_posting.deleted",
  "analytics.export.requested",
  "analytics.export.succeeded",
  "analytics.export.failed",
  "analytics.export.downloaded",
  "analytics.export.expired",
  "SCORING_RESCORE_REQUESTED",
  "APPLICATION_SCORING_REQUESTED",
  "AI_RETRY_REQUESTED",
  "MANUAL_PRIORITY_SET",
  "MANUAL_PRIORITY_REMOVED",
  "APPLICATION_MOVED_TO_INTERVIEW",
  "APPLICATION_REJECTED",
  "messaging.conversation.opened",
  "messaging.conversation.denied",
  "messaging.participant.blocked",
  "messaging.participant.unblocked",
  "messaging.report.submitted",
  "cv_import.reserved",
  "cv_import.content_received",
  "cv_import.stage_completed",
  "cv_import.retry_requested",
  "cv_import.draft_saved",
  "cv_import.confirmed",
  "cv_import.deleted",
  "cv_import.expired",
  "cv_import.consent_granted",
  "cv_import.consent_revoked",
  "cv_import.cleanup_completed",
  "cv_import.cleanup_failed",
  "cv_import.external_dispatch_completed",
  "cv_import.external_dispatch_failed",
  "cv_import.content_scrubbed",
  "cv_import.reconciled",
  "ocr.stage_completed",
  "ocr.stage_failed",
  "image_search.admitted",
  "image_search.denied",
  "image_search.stage_completed",
  "image_search.stage_failed",
  "image_search.consent_granted",
  "image_search.consent_revoked",
  "image_search.consumed",
  "image_search.cancelled",
  "image_search.expired",
  "image_search.content_scrubbed",
  "image_search.cleanup_completed",
  "image_search.cleanup_failed",
  "image_search.reconciled",
  "admin.access_denied",
  "admin.company_detail_viewed",
  "admin.session_designated",
  "admin.step_up_completed",
  "admin.account_suspended",
  "admin.account_reinstated",
  "admin.account_restored",
  "admin.session_revoked",
  "admin.sessions_revoked_all",
  "admin.membership_suspended",
  "admin.membership_restored",
  "admin.membership_removed",
  "admin.company_banned",
  "admin.company_unbanned",
  "admin.verification_changes_requested",
  "admin.verification_approved",
  "admin.verification_rejected",
  "admin.report_assigned",
  "admin.report_noted",
  "admin.report_resolved",
  "admin.report_dismissed",
  "admin.report_enforcement_linked",
  "support.case_created",
  "support.message_sent",
  "admin.support_claimed",
  "admin.support_reassigned",
  "admin.support_replied",
  "admin.support_noted",
  "admin.support_resolved",
  "admin.support_closed",
  "support.case_reopened",
  "support.case_auto_closed",
  "support.assignment_requeued",
  "support.content_deleted",
  "admin.connection_proposal_created",
  "admin.connection_proposal_cancelled",
  "connection.proposal_accepted",
  "connection.proposal_declined",
  "connection.proposal_expired",
  "connection.proposal_cancelled",
  "connection.created",
  "connection.revoked",
  "connection.notification_read",
  "connection.content_deleted",
  "job_post_review.submitted",
  "job_post_review.claimed",
  "job_post_review.reassigned",
  "job_post_review.approved",
  "job_post_review.rejected",
  "job_post_review.approval_blocked",
  "job_post_review.closed",
  "job_post_review.withdrawn",
  "job_post_review.retention_purged",
  "job_post_management.hide",
  "job_post_management.restore",
  "job_post_management.close_applications",
  "job_post_management.reopen_applications",
  "job_post_management.archive",
  "job_post_management.soft_delete",
  "job_post_management.request_changes",
  "job_post_management.feature",
  "job_post_management.unfeature",
  "job_post_management.enforce",
]);

const auditContextSchema = z
  .object({
    reason: z.string().max(160).optional(),
    stage: z.string().max(160).optional(),
    state: z.string().max(160).optional(),
    status: z.string().max(160).optional(),
    kind: z.string().max(160).optional(),
    failureCode: z.string().max(160).optional(),
    count: z.number().finite().optional(),
    format: z.enum(["CSV", "XLSX"]).optional(),
    capacity: z.number().int().positive().optional(),
    finalScore: z.number().finite().optional(),
    attemptCount: z.number().finite().optional(),
    holdHours: z.number().finite().optional(),
    eligible: z.boolean().optional(),
    passwordOwner: z.string().max(160).optional(),
    sessionRevocation: z.string().max(160).optional(),
    twoFactorPreserved: z.boolean().optional(),
    sessionsRevoked: z.boolean().optional(),
    otherSessionsRevoked: z.boolean().optional(),
    challengesInvalidated: z.boolean().optional(),
    previousSessionsRemainRevoked: z.boolean().optional(),
    twoFactorDisabled: z.boolean().optional(),
    backupCodesInvalidated: z.boolean().optional(),
    automaticSessionCreated: z.boolean().optional(),
    duplicate: z.boolean().optional(),
    notificationWorkCount: z.number().int().nonnegative().optional(),
    fromStage: z.string().max(40).optional(),
    toStage: z.string().max(40).optional(),
    applicationVersion: z.number().int().positive().optional(),
    parserClass: z
      .enum(["DETERMINISTIC_INTERNAL", "EXTERNAL_OPENAI"])
      .optional(),
    schemaVersion: z.string().max(100).optional(),
    noticeVersion: z.string().max(100).optional(),
    revision: z.number().int().min(0).optional(),
    durationBucket: z.string().max(40).optional(),
    lagBucket: z.string().max(40).optional(),
    purpose: z.enum(["CV_IMPORT", "JOB_IMAGE_SEARCH"]).optional(),
    actorClass: z.enum(["VISITOR", "AUTHENTICATED", "SYSTEM"]).optional(),
    byteBucket: z.string().max(40).optional(),
    pixelBucket: z.string().max(40).optional(),
    countBucket: z.string().max(40).optional(),
    engineVersion: z.string().max(40).optional(),
    modelVersion: z.string().max(160).optional(),
    policyVersion: z.string().max(100).optional(),
    consentPresent: z.boolean().optional(),
    consentRevoked: z.boolean().optional(),
    retryOutcome: z.string().max(40).optional(),
    deletionResult: z.string().max(40).optional(),
    reasonCategory: z.string().max(80).optional(),
    priorState: z.string().max(80).optional(),
    resultingState: z.string().max(80).optional(),
    targetVersion: z.number().int().nonnegative().optional(),
    companyReference: z.string().max(128).optional(),
    visibility: z.string().max(80).optional(),
    applicationState: z.string().max(80).optional(),
    outcome: z.string().max(80).optional(),
    preservedStage: z.string().max(40).optional(),
  })
  .strict();

export const authenticationAuditEventSchema = z
  .object({
    occurredAt: z.date(),
    actorType: z.enum(["anonymous", "user", "system"]),
    actorUserId: z.string().min(1).nullable().optional(),
    actorSessionId: z.string().min(1).nullable().optional(),
    action: authenticationAuditAction,
    targetType: z.enum([
      "user_account",
      "email_verification",
      "request",
      "email_outbox",
      "session",
      "two_factor",
      "password_reset",
      "account_recovery",
      "email_change",
      "password_change",
      "job_posting",
      "job_report",
      "job_application",
      "messaging_conversation",
      "cv_import",
      "cv_draft",
      "cv_consent",
      "cv_confirmation",
      "ocr_attempt",
      "image_search",
      "image_search_consent",
      "administrator_grant",
      "administrator_session_policy",
      "company",
      "company_membership",
      "recruiter_verification",
      "moderation_report",
      "messaging_report",
      "privileged_action",
      "security_notification",
      "support_case",
      "connection_proposal",
      "professional_connection",
      "connection_notification",
      "job_post_review",
      "export_request",
    ]),
    targetId: z.string().min(1).nullable().optional(),
    result: z.enum(["SUCCESS", "FAILURE", "DENIED"]),
    correlationId: z.string().min(8).max(128),
    ipPrefixDigest: z.string().max(128).nullable().optional(),
    userAgentFamily: z.string().max(80).nullable().optional(),
    context: auditContextSchema,
  })
  .strict();

export type AuthenticationAuditEvent = z.infer<
  typeof authenticationAuditEventSchema
>;
