import type { WorkspaceLocale } from "@/frontend/features/dashboard/client/workspace-locale";

export function messagingCopy(locale: WorkspaceLocale) {
  return locale === "vi"
    ? {
        workspaceKicker: "KHÔNG GIAN ỨNG VIÊN",
        pageTitle: "Tin nhắn",
        pageDescription:
          "Kết nối với nhà tuyển dụng trong một không gian làm việc an toàn.",
        connected: "Đang kết nối trực tuyến",
        connecting: "Đang kết nối",
        reconnecting: "Đang kết nối lại",
        offline: "Ngoại tuyến",
        recentConversations: "Cuộc trò chuyện gần đây",
        conversations: "cuộc trò chuyện",
        noConversations: "Chưa có cuộc trò chuyện nào",
        noConversationsDescription:
          "Tin nhắn sẽ xuất hiện khi bạn ứng tuyển hoặc kết nối với nhà tuyển dụng.",
        readyToChat: "Sẵn sàng trò chuyện",
        youPrefix: "Bạn: ",
        unread: "tin nhắn chưa đọc",
        loadMore: "Xem thêm cuộc trò chuyện",
        eligibleKicker: "KẾT NỐI",
        eligiblePeople: "Người có thể nhắn",
        openConversationError:
          "Không thể mở cuộc trò chuyện. Vui lòng thử lại.",
        conversationContext: "Ngữ cảnh cuộc trò chuyện",
        messagePerson: "Nhắn tin cho",
        opening: "Đang mở…",
        message: "Tin nhắn",
        professionalConnection: "Kết nối chuyên nghiệp",
        jobConversation: "Tin nhắn về vị trí ứng tuyển",
        viewJob: "Xem tin tuyển dụng →",
        online: "Đang trực tuyến",
        backToConversations: "Quay lại danh sách cuộc trò chuyện",
        threadWith: "Cuộc trò chuyện với",
        loadConversationError: "Không thể tải cuộc trò chuyện này",
        inboxTitle: "Cuộc trò chuyện",
        selectConversation: "Chọn một cuộc trò chuyện để xem tin nhắn.",
        privacyNotice:
          "Tin nhắn được bảo mật riêng tư, lưu trữ lâu dài và được bảo vệ trong phiên đăng nhập SmartHire của bạn.",
        applyForJobs: "Xem việc làm phù hợp",
        viewConnections: "Xem danh bạ kết nối",
        connectionEnded:
          "Kết nối này đã kết thúc. Lịch sử trò chuyện được giữ ở chế độ chỉ đọc.",
        blockedConversation:
          "Bạn đã chặn nhắn tin. Lịch sử trò chuyện vẫn khả dụng.",
        loadOlder: "Tải tin nhắn cũ hơn",
        conversationStarted: "Bắt đầu cuộc trò chuyện",
        deliveryRead: "Đã xem",
        deliverySent: "Đã gửi",
        composeMessage: "Soạn tin nhắn",
        sendingMessages: "Tin nhắn đang gửi",
        validation: "Nhập từ 1 đến 2.000 ký tự.",
        sending: "Đang gửi",
        send: "Gửi",
        sendFailed: "Không gửi được",
        retry: "Thử lại",
        readOnlyConversation: "Cuộc trò chuyện ở chế độ chỉ đọc",
        writeMessage: "Viết tin nhắn…",
        sendHint: "Nhấn Enter để gửi · Shift + Enter để xuống dòng",
        block: "Chặn",
        unblock: "Bỏ chặn",
        safetyError: "Không thể cập nhật cài đặt an toàn.",
        continueMessaging: "Tiếp tục nhắn tin?",
        stopContact: "Dừng liên lạc?",
        blockDescription:
          "Lịch sử tin nhắn vẫn được lưu. Chặn sẽ dừng ngay việc nhắn tin mới và chia sẻ trạng thái trực tuyến.",
        saving: "Đang lưu…",
        confirm: "Xác nhận",
        cancel: "Huỷ",
        report: "Báo cáo",
        reportConversation: "Báo cáo cuộc trò chuyện",
        reportInappropriate: "Báo cáo nội dung không phù hợp",
        reportDescription:
          "Báo cáo của bạn được giữ riêng tư và xem xét qua quy trình bảo mật.",
        category: "Danh mục",
        evidence: "Tin nhắn làm bằng chứng (không bắt buộc)",
        noEvidence: "Không chọn tin nhắn cụ thể",
        detail: "Chi tiết (không bắt buộc)",
        detailPlaceholder: "Bổ sung thông tin hỗ trợ việc xem xét…",
        reportValidation: "Vui lòng nhập ít nhất 10 ký tự khi chọn Khác.",
        reportSuccess:
          "Đã nhận báo cáo và chuyển đến quy trình xem xét bảo mật.",
        reportError: "Không thể gửi báo cáo. Vui lòng thử lại.",
        submitReport: "Gửi báo cáo",
        close: "Đóng",
        conversationRefreshError: "Không thể làm mới cuộc trò chuyện.",
        olderConversationsError: "Không thể tải các cuộc trò chuyện cũ hơn.",
        messagesLoadError: "Không thể tải tin nhắn.",
        olderMessagesError: "Không thể tải tin nhắn cũ hơn.",
        reportCategories: [
          ["FRAUD_OR_IMPERSONATION", "Lừa đảo hoặc mạo danh"],
          ["MISLEADING_CONTENT", "Nội dung gây hiểu lầm"],
          ["DISCRIMINATION_OR_HARASSMENT", "Phân biệt đối xử hoặc quấy rối"],
          ["ABUSE_OR_THREATS", "Lạm dụng hoặc đe doạ"],
          ["SPAM_OR_DUPLICATE", "Tin rác"],
          ["PRIVACY_OR_DATA_MISUSE", "Lạm dụng quyền riêng tư hoặc dữ liệu"],
          ["OTHER", "Khác"],
        ],
      }
    : {
        workspaceKicker: "CANDIDATE WORKSPACE",
        pageTitle: "Messages",
        pageDescription: "Connect with hiring teams in a secure workspace.",
        connected: "Realtime connected",
        connecting: "Connecting",
        reconnecting: "Reconnecting",
        offline: "Offline",
        recentConversations: "Recent conversations",
        conversations: "conversations",
        noConversations: "No conversations yet",
        noConversationsDescription:
          "Messages appear when you apply for a role or connect with a recruiter.",
        readyToChat: "Ready to chat",
        youPrefix: "You: ",
        unread: "unread messages",
        loadMore: "Load more conversations",
        eligibleKicker: "CONNECTIONS",
        eligiblePeople: "People you can message",
        openConversationError:
          "Unable to open this conversation. Please try again.",
        conversationContext: "Conversation context",
        messagePerson: "Message",
        opening: "Opening…",
        message: "Message",
        professionalConnection: "Professional connection",
        jobConversation: "Conversation about this application",
        viewJob: "View job posting →",
        online: "Online",
        backToConversations: "Back to conversations",
        threadWith: "Conversation with",
        loadConversationError: "Unable to load this conversation",
        inboxTitle: "Conversations",
        selectConversation: "Select a conversation to read messages.",
        privacyNotice:
          "Messages are private, durable, and protected by your SmartHire session.",
        applyForJobs: "Browse suitable jobs",
        viewConnections: "View connections",
        connectionEnded:
          "This connection has ended. The conversation history remains read-only.",
        blockedConversation:
          "You have blocked messaging. The conversation history remains available.",
        loadOlder: "Load older messages",
        conversationStarted: "Conversation started",
        deliveryRead: "Read",
        deliverySent: "Sent",
        composeMessage: "Compose message",
        sendingMessages: "Messages sending",
        validation: "Enter between 1 and 2,000 characters.",
        sending: "Sending",
        send: "Send",
        sendFailed: "Unable to send",
        retry: "Retry",
        readOnlyConversation: "This conversation is read-only",
        writeMessage: "Write a message…",
        sendHint: "Press Enter to send · Shift + Enter for a new line",
        block: "Block",
        unblock: "Unblock",
        safetyError: "Unable to update safety settings.",
        continueMessaging: "Continue messaging?",
        stopContact: "Stop contact?",
        blockDescription:
          "The message history remains saved. Blocking immediately stops new messages and presence sharing.",
        saving: "Saving…",
        confirm: "Confirm",
        cancel: "Cancel",
        report: "Report",
        reportConversation: "Report conversation",
        reportInappropriate: "Report inappropriate content",
        reportDescription:
          "Your report is private and reviewed through our safety process.",
        category: "Category",
        evidence: "Evidence message (optional)",
        noEvidence: "Do not select a specific message",
        detail: "Details (optional)",
        detailPlaceholder: "Add information that can help our review…",
        reportValidation: "Enter at least 10 characters when selecting Other.",
        reportSuccess:
          "Your report was received and sent to our safety review process.",
        reportError: "Unable to submit the report. Please try again.",
        submitReport: "Submit report",
        close: "Close",
        conversationRefreshError: "Unable to refresh conversations.",
        olderConversationsError: "Unable to load older conversations.",
        messagesLoadError: "Unable to load messages.",
        olderMessagesError: "Unable to load older messages.",
        reportCategories: [
          ["FRAUD_OR_IMPERSONATION", "Fraud or impersonation"],
          ["MISLEADING_CONTENT", "Misleading content"],
          ["DISCRIMINATION_OR_HARASSMENT", "Discrimination or harassment"],
          ["ABUSE_OR_THREATS", "Abuse or threats"],
          ["SPAM_OR_DUPLICATE", "Spam"],
          ["PRIVACY_OR_DATA_MISUSE", "Privacy or data misuse"],
          ["OTHER", "Other"],
        ],
      };
}
