import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { prisma } from "@/backend/database/prisma";
import { VerificationReviewService } from "@/backend/admin/verification/verification-review-service";
import { VerificationApprovalTransaction } from "@/backend/admin/verification/verification-approval-transaction";

const suffix = crypto.randomUUID(); const applicantId = `verification-applicant-${suffix}`; const requestId = `verification-request-${suffix}`; const evidenceId = `verification-evidence-${suffix}`; const authority = { userId: `admin-${suffix}`, sessionId: `session-${suffix}`, grantId: `grant-${suffix}`, proofAt: new Date() };
describe("verification decisions", () => { beforeEach(async () => { await prisma.userAccount.create({ data: { id: applicantId, name: "Applicant", email: `${applicantId}@example.test`, normalizedEmail: `${applicantId}@example.test`, state: "ACTIVE", emailVerified: true, candidateIdentity: { create: {} } } }); await prisma.recruiterVerificationRequest.create({ data: { id: requestId, applicantUserId: applicantId, submittedCompanyName: `Verified Company ${suffix}`, normalizedTaxIdentifier: suffix.replace(/\D/gu, "").padEnd(10, "0").slice(0, 10), requestedRole: "RECRUITER", state: "PENDING_REVIEW", currentEvidenceId: evidenceId, evidence: { create: { id: evidenceId, submissionVersion: 1, declaredMediaType: "application/pdf", detectedMediaType: "application/pdf", byteSize: 100, sourceSha256: "a".repeat(64), storageAdapter: "filesystem", storageLocator: `unused-${suffix}`, encryptionKeyVersion: 1, iv: "unused", authenticationTag: "unused", malwareStatus: "PASS", typeStatus: "PASS", structureStatus: "PASS", previewStatus: "PASS", reviewableAt: new Date() } } } }); }); afterEach(async () => { await prisma.emailOutbox.deleteMany({ where: { verificationRequestId: requestId } }); await prisma.adminCommandReceipt.deleteMany({ where: { targetReference: requestId } }); const request = await prisma.recruiterVerificationRequest.findUnique({ where: { id: requestId }, select: { targetCompanyId: true } }); await prisma.recruiterVerificationRequest.deleteMany({ where: { id: requestId } }); if (request?.targetCompanyId) { await prisma.companyMembership.deleteMany({ where: { companyId: request.targetCompanyId } }); await prisma.company.deleteMany({ where: { id: request.targetCompanyId } }); } await prisma.candidateIdentity.delete({ where: { userId: applicantId } }); await prisma.userAccount.delete({ where: { id: applicantId } }); });
  it("commits request-changes, history, private note, audit, and one applicant outbox row", async () => { await new VerificationReviewService().requestChanges(authority, requestId, { expectedVersion: 1, idempotencyKey: crypto.randomUUID(), guidance: "Please submit a clearer complete license.", privateNote: "Internal review complete." }); const row = await prisma.recruiterVerificationRequest.findUniqueOrThrow({ where: { id: requestId }, include: { decisions: true, notes: true, notifications: true } }); expect(row.state).toBe("CHANGES_REQUESTED"); expect(row.decisions).toHaveLength(1); expect(row.notes).toHaveLength(1); expect(row.notifications).toHaveLength(1); });
  it("allows exactly one concurrent new-company approval and creates one OWNER membership", async () => { const transaction = new VerificationApprovalTransaction(); const commands = [1, 2].map(() => ({ expectedVersion: 1, idempotencyKey: crypto.randomUUID(), role: "RECRUITER" as const })); const results = await Promise.allSettled(commands.map((command) => transaction.execute(authority, requestId, command))); expect(results.filter((item) => item.status === "fulfilled")).toHaveLength(1); expect(results.filter((item) => item.status === "rejected")).toHaveLength(1); const row = await prisma.recruiterVerificationRequest.findUniqueOrThrow({ where: { id: requestId }, include: { targetCompany: { include: { memberships: true } }, notifications: true } }); expect(row.state).toBe("APPROVED"); expect(row.targetCompany?.memberships).toHaveLength(1); expect(row.targetCompany?.memberships[0]?.role).toBe("OWNER"); expect(row.notifications).toHaveLength(1); });
});
